Repository cda-tum/fiction, pull requests merged in 2022-12, with the labels that each got.

#82 :green_heart: Added fixes for MSVC 2022's `C2760` and `C3878` by utilizing type specifiers instead of types for casting and variable declaration
  test/layouts/gate_level_layout.cpp
Labels: bug, compiler issue

#81 :green_heart: Fixed GitHub Actions' wildcard paths resolves
  .github/workflows/clang-tidy-review.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/coverage.yml
  .github/workflows/docker-image.yml
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
Labels: bug, github_actions

#80 :bug: added "const" for return iterator of "find" function
  include/fiction/layouts/cell_level_layout.hpp
Labels: small fix

#84 new constructor for sidb_surface.cpp added
  include/fiction/technology/sidb_surface.hpp
  test/technology/sidb_surface.cpp
Labels: enhancement

#85 :zap: Made distance functions `constexpr`
  include/fiction/algorithms/path_finding/distance.hpp
Labels: small fix

#88 :bug: Fix number regex
  include/fiction/io/read_fqca_layout.hpp
Labels: bug
