Repository cda-tum/fiction, pull requests merged in 2023-06, with the labels that each got.

#225 🐛 Bug fixes and improvements related to the coordinate system
  include/fiction/algorithms/physical_design/apply_gate_library.hpp
  include/fiction/io/print_layout.hpp
  include/fiction/layouts/cartesian_layout.hpp
  include/fiction/layouts/coordinates.hpp
  include/fiction/layouts/hexagonal_layout.hpp
  include/fiction/utils/layout_utils.hpp
  include/fiction/utils/math_utils.hpp
  test/io/print_layout.cpp
  test/layouts/cartesian_layout.cpp
  test/layouts/coordinates.cpp
  test/utils/layout_utils.cpp
  test/utils/math_utils.cpp
Labels: bug, small fix

#198 ✨ Added a hexagonalization algorithm for mapping QCA layouts to SiDB ones
  cli/cmd/physical_design/hex.hpp
  cli/commands.hpp
  docs/_static/hexagonalization.svg
  docs/algorithms/algorithms.rst
  docs/algorithms/hexagonalization.rst
  docs/publications.rst
  experiments/hexagonalization/hexagonalization.cpp
  include/fiction/algorithms/physical_design/hexagonalization.hpp
  test/algorithms/physical_design/hexagonalization.cpp
  test/utils/blueprints/layout_blueprints.hpp
Labels: enhancement

#233 ✨ Add function to generate a random coordinate.
  docs/utils/utils.rst
  include/fiction/utils/layout_utils.hpp
  test/utils/layout_utils.cpp
Labels: enhancement

#240 :sparkles: Added a unified `print_layout` function
  docs/io/visualization.rst
  include/fiction/io/print_layout.hpp
  test/io/print_layout.cpp
Labels: enhancement

#241 🐛 Missing physical validity check in quicksim for special cases
  include/fiction/algorithms/simulation/sidb/is_ground_state.hpp
  include/fiction/algorithms/simulation/sidb/quicksim.hpp
  test/algorithms/simulation/sidb/quicksim.cpp
Labels: bug
