Repository cda-tum/fiction, pull requests merged in 2023-04, with the labels that each got.

#185 ✨ Added Z3 toggle to the `pyfiction` build process
  .github/workflows/python-bindings.yml
  .gitignore
  bindings/pyfiction/test/algorithms/physical_design/test_apply_gate_library.py
  bindings/pyfiction/test/algorithms/physical_design/test_exact.py
  bindings/pyfiction/test/algorithms/simulation/test_logic_simulation.py
  setup.py
Labels: enhancement

#186 redefinition of sidb_nm_position
  include/fiction/algorithms/simulation/sidb/sidb_simulation_parameters.hpp
  include/fiction/technology/charge_distribution_surface.hpp
  include/fiction/technology/sidb_nm_position.hpp
  test/technology/charge_distribution_surface.cpp
Labels: small fix

#188 :art: Changed the unit of the lambda-tf physical parameter from meter to nanometer
  include/fiction/algorithms/simulation/sidb/sidb_simulation_parameters.hpp
  include/fiction/technology/charge_distribution_surface.hpp
  test/technology/charge_distribution_surface.cpp
Labels: small fix

#189 :sparkles: Added a function to round a number to `n` decimal places
  include/fiction/algorithms/simulation/sidb/energy_distribution.hpp
  include/fiction/utils/math_utils.hpp
  test/utils/math_utils.cpp
Labels: enhancement

#176 :sparkles: Added an SiDB simulation file writer
  docs/algorithms/sidb_simulation.rst
  docs/io/physical_simulation.rst
  include/fiction/algorithms/simulation/sidb/sidb_simulation_result.hpp
  include/fiction/io/write_sqd_layout.hpp
  include/fiction/io/write_sqd_sim_result.hpp
  test/io/write_sqd_sim_result.cpp
Labels: enhancement

#194 :white_check_mark: Ensured a reproducible SiDB order for test reproducibility
  include/fiction/io/write_sqd_sim_result.hpp
  include/fiction/technology/charge_distribution_surface.hpp
  test/io/write_sqd_sim_result.cpp
Labels: bug, test

#195 🐛 Fix test skips based on Z3
  .github/workflows/pyfiction-pypi-deployment.yml
  .github/workflows/python-bindings.yml
  bindings/pyfiction/README.md
  bindings/pyfiction/test/algorithms/physical_design/test_apply_gate_library.py
  bindings/pyfiction/test/algorithms/physical_design/test_exact.py
  pyproject.toml
Labels: bug

#177 :sparkles: Make ClangFormat aware of different line ending types and enforce `LF`
  .clang-format
  .github/workflows/clang-format.yml
  .github/workflows/clang-tidy-review.yml
  experiments/bestagon/bestagon.cpp
  experiments/color_routing/color_routing.cpp
  experiments/defect_aware_physical_design/defect_aware_physical_design.cpp
  experiments/defect_aware_physical_design/generate_defective_surface.py
  experiments/libfiction_demo.cpp
  include/fiction/algorithms/path_finding/a_star.hpp
  include/fiction/algorithms/path_finding/jump_point_search.hpp
  include/fiction/algorithms/physical_design/one_pass_synthesis.hpp
  include/fiction/io/read_fqca_layout.hpp
  include/fiction/io/write_qcc_layout.hpp
  include/fiction/io/write_qll_layout.hpp
  test/algorithms/path_finding/a_star.cpp
  test/algorithms/path_finding/enumerate_all_paths.cpp
  test/algorithms/path_finding/jump_point_search.cpp
  test/algorithms/path_finding/k_shortest_paths.cpp
  test/algorithms/physical_design/exact.cpp
  test/algorithms/physical_design/one_pass_synthesis.cpp
Labels: enhancement, github_actions

#190 ✨ Added `pyfiction` documentation to read the docs
  .github/workflows/clang-tidy-review.yml
  .readthedocs.yml
  bindings/pyfiction/include/pyfiction/algorithms/physical_design/exact.hpp
  bindings/pyfiction/include/pyfiction/documentation.hpp
  bindings/pyfiction/include/pyfiction/layouts/cartesian_layout.hpp
  bindings/pyfiction/include/pyfiction/layouts/hexagonal_layout.hpp
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  docs/algorithms/apply_gate_library.rst
  docs/algorithms/color_routing.rst
  docs/algorithms/exact.rst
  docs/algorithms/graph.rst
  docs/algorithms/network_transformation.rst
  docs/algorithms/orthogonal.rst
  docs/algorithms/path_finding.rst
  docs/algorithms/properties.rst
  docs/algorithms/verification.rst
  docs/conf.py
  docs/io/input.rst
  docs/io/physical_simulation.rst
  docs/io/visualization.rst
  docs/layouts/cartesian_layout.rst
  docs/layouts/cell_level_layout.rst
  docs/layouts/clocked_layout.rst
  docs/layouts/coordinates.rst
  docs/layouts/gate_level_layout.rst
  docs/layouts/hexagonal_layout.rst
  docs/layouts/obstruction_layout.rst
  docs/requirements.txt
  docs/technology/cell_technologies.rst
  docs/technology/properties.rst
  docs/utils/utils.rst
  include/fiction/algorithms/graph/graph_coloring.hpp
  include/fiction/algorithms/iter/aspect_ratio_iterator.hpp
  include/fiction/algorithms/network_transformation/fanout_substitution.hpp
  include/fiction/algorithms/optimization/simulated_annealing.hpp
  include/fiction/algorithms/path_finding/a_star.hpp
  include/fiction/algorithms/path_finding/distance.hpp
  include/fiction/algorithms/path_finding/k_shortest_paths.hpp
  include/fiction/algorithms/physical_design/color_routing.hpp
  include/fiction/algorithms/physical_design/exact.hpp
  include/fiction/algorithms/physical_design/one_pass_synthesis.hpp
  include/fiction/algorithms/physical_design/orthogonal.hpp
  include/fiction/algorithms/properties/critical_path_length_and_throughput.hpp
  include/fiction/algorithms/simulation/sidb/is_ground_state.hpp
  include/fiction/algorithms/verification/equivalence_checking.hpp
  include/fiction/io/write_svg_layout.hpp
  include/fiction/layouts/cartesian_layout.hpp
  include/fiction/layouts/cell_level_layout.hpp
  include/fiction/layouts/coordinates.hpp
  include/fiction/layouts/hexagonal_layout.hpp
  include/fiction/technology/charge_distribution_surface.hpp
  include/fiction/technology/fcn_gate_library.hpp
  include/fiction/technology/inml_topolinano_library.hpp
  include/fiction/technology/physical_constants.hpp
  include/fiction/technology/qca_one_library.hpp
Labels: enhancement, documentation
