Repository cda-tum/fiction, pull requests merged in 2023-07, with the labels that each got.

#246 :art: add ``assertLessEqual``.
  bindings/pyfiction/test/algorithms/simulation/sidb/test_quicksim.py
Labels: test

#249 :memo: Fixed remaining fragments from the move to `cda-tum` and adjusted the tracking of publications
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  Dockerfile
  README.md
  docs/contributing.rst
  docs/publications.rst
  docs/support.rst
  include/fiction/algorithms/physical_design/hexagonalization.hpp
  include/fiction/algorithms/simulation/sidb/critical_temperature.hpp
  include/fiction/algorithms/simulation/sidb/quicksim.hpp
  include/fiction/utils/version_info.hpp.in
Labels: documentation, small fix

#250 :sparkles: Added additional distance functions and distance maps
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
  docs/algorithms/path_finding.rst
  docs/getting_started.rst
  include/fiction/algorithms/path_finding/distance.hpp
  include/fiction/algorithms/path_finding/distance_map.hpp
  test/CMakeLists.txt
  test/algorithms/path_finding/distance.cpp
  test/algorithms/path_finding/distance_map.cpp
  test/benchmark/CMakeLists.txt
  test/benchmark/distance_map.cpp
Labels: enhancement

#254 🎨 Use unit library for sidb defects.
  docs/utils/utils.rst
  include/fiction/io/read_sqd_layout.hpp
  include/fiction/io/write_sqd_layout.hpp
  include/fiction/technology/sidb_defects.hpp
  include/fiction/utils/units_utils.hpp
  test/io/read_sqd_layout.cpp
  test/technology/sidb_defects.cpp
Labels: enhancement

#256 :bug: Fix `equivalence_checking` on `obstruction_layout` objects
  include/fiction/layouts/obstruction_layout.hpp
  test/algorithms/verification/equivalence_checking.cpp
Labels: bug

#257 :bug: 2DDWave Distance Fix
  include/fiction/algorithms/path_finding/distance.hpp
  test/algorithms/path_finding/distance.cpp
  test/algorithms/path_finding/distance_map.cpp
Labels: bug

#259 ✅ Add missing unit test for sidb distance
  test/algorithms/path_finding/distance.cpp
  test/technology/sidb_nm_position.cpp
Labels: test
