Repository cda-tum/fiction, pull requests merged in 2023-11, with the labels that each got.

#327 :bug: Fixed a bug that caused pre-mature termination of `sidb_surface_analysis`
  include/fiction/technology/sidb_surface_analysis.hpp
Labels: bug

#326 🐛 The dependent cell is now linked correctly to the simulation base number in SiDB simulation
  include/fiction/algorithms/simulation/sidb/quickexact.hpp
  include/fiction/technology/charge_distribution_surface.hpp
  test/algorithms/simulation/sidb/quickexact.cpp
  test/technology/charge_distribution_surface.cpp
Labels: bug

#330 :alembic: Updated the atomic defect-aware SiDB physical design experiment in accordance with the final paper
  docs/technology/properties.rst
  experiments/defect_aware_physical_design/defect_aware_physical_design.cpp
  include/fiction/technology/area.hpp
Labels: bug, enhancement

#329 :art: Fix urgent CodeQL warnings.
  include/fiction/algorithms/simulation/sidb/calculate_energy_and_state_type.hpp
  include/fiction/algorithms/simulation/sidb/critical_temperature.hpp
  include/fiction/algorithms/simulation/sidb/occupation_probability_of_excited_states.hpp
  test/algorithms/path_finding/distance.cpp
  test/algorithms/simulation/sidb/quickexact.cpp
  test/algorithms/simulation/sidb/quicksim.cpp
  test/technology/sidb_nm_position.cpp
  test/utils/layout_utils.cpp
Labels: bug

#331 🐛 Correct y-direction boundary for Moore neighborhood
  include/fiction/algorithms/simulation/sidb/operational_domain.hpp
  test/algorithms/simulation/sidb/operational_domain.cpp
Labels: bug

#248 :sparkles: MIG inverter optimization and propagation
  cli/cmd/logic/miginvopt.hpp
  cli/cmd/logic/miginvprop.hpp
  cli/commands.hpp
Labels: enhancement, cli

#337 :file_folder: Case style of experiments folders corrected in fiction_experiments.hpp
  experiments/fiction_experiments.hpp
Labels: bug

#339 :open_umbrella: Added Codecov configuration file
  .codecov.yml
Labels: small fix

#338 :sparkles: Benchmark for physical simulators.
  test/benchmark/simulation.cpp
Labels: enhancement

#341 :hook: Set up pre-commit checks
  .github/release-drafter.yml
  .github/workflows/codeql-analysis.yml
  .pre-commit-config.yaml
  CMakeLists.txt
  cli/CMakeLists.txt
  cli/cmd/io/tt.hpp
  cli/cmd/logic/miginvopt.hpp
  cli/cmd/physical_design/exact.hpp
  cmake/Cache.cmake
  cmake/CheckSubmodules.cmake
  cmake/CompilerWarnings.cmake
  cmake/Coverage.cmake
  cmake/FindTBB.cmake
  cmake/FindZ3.cmake
  cmake/Hardening.cmake
  cmake/InterproceduralOptimization.cmake
  cmake/PackageProject.cmake
  cmake/PreventInSourceBuilds.cmake
  cmake/ProjectOptions.cmake
  cmake/Sanitizers.cmake
  cmake/StandardProjectSettings.cmake
  cmake/SystemLink.cmake
  cmake/Utilities.cmake
  cmake/VCEnvironment.cmake
  docs/_static/hexagonalization.svg
  docs/cli.rst
  docs/layouts/gate_level_layout.rst
  docs/utils/utils.rst
  experiments/CMakeLists.txt
  include/CMakeLists.txt
  test/CMakeLists.txt
  test/benchmark/CMakeLists.txt
  test/io/print_layout.cpp
Labels: enhancement

#342 🐛 Place inputs and outputs in the same order during hexagonalization
  include/fiction/algorithms/physical_design/hexagonalization.hpp
Labels: bug

#343 :bug: The critical temperature value will only be overwritten by the new value if the new value is lower.
  include/fiction/algorithms/simulation/sidb/critical_temperature.hpp
  test/algorithms/simulation/sidb/critical_temperature.cpp
Labels: bug
