Repository cda-tum/fiction, pull requests merged in 2023-09, with the labels that each got.

#274 📝 Update publication list
  docs/publications.rst
  include/fiction/algorithms/simulation/sidb/critical_temperature.hpp
  include/fiction/algorithms/simulation/sidb/quicksim.hpp
Labels: documentation

#276 :construction_worker: Reduce `clang-tidy` warnings in unwanted cases
  .clang-tidy
Labels: github_actions

#200 ✨ Added function to generate random SiDB layouts and write simulation results to file.
  docs/algorithms/sidb_simulation.rst
  docs/io/physical_simulation.rst
  experiments/random_sidb_layout_generation/random_sidb_layout_generation.cpp
  experiments/random_sidb_layout_generation/sidb_location_and_ground_state_simulation.cpp
  include/fiction/algorithms/simulation/sidb/random_sidb_layout_generator.hpp
  include/fiction/io/write_location_and_ground_state.hpp
  test/algorithms/simulation/sidb/random_sidb_layout_generator.cpp
  test/io/write_location_and_ground_state.cpp
  test/io/write_sqd_layout.cpp
Labels: enhancement

#277 🔧 enable GitHub workflow concurrency
  .github/workflows/clang-format.yml
  .github/workflows/clang-tidy-review.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/coverage.yml
  .github/workflows/docker-image.yml
  .github/workflows/macos.yml
  .github/workflows/release-drafter.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
Labels: github_actions

#279 :sparkles: Enhanced pathfinding versatility
  docs/algorithms/path_finding.rst
  include/fiction/algorithms/graph/generate_edge_intersection_graph.hpp
  include/fiction/algorithms/path_finding/a_star.hpp
  include/fiction/algorithms/path_finding/enumerate_all_paths.hpp
  include/fiction/algorithms/path_finding/jump_point_search.hpp
  include/fiction/algorithms/path_finding/k_shortest_paths.hpp
  include/fiction/algorithms/physical_design/orthogonal.hpp
  include/fiction/algorithms/properties/critical_path_length_and_throughput.hpp
  test/algorithms/path_finding/a_star.cpp
  test/algorithms/path_finding/distance.cpp
  test/algorithms/path_finding/enumerate_all_paths.cpp
  test/algorithms/path_finding/jump_point_search.cpp
  test/algorithms/path_finding/k_shortest_paths.cpp
Labels: enhancement

#203 ✨ New SiDB simulator ``QuickExact`` and simulation of atomic defects.
  docs/algorithms/iterators.rst
  docs/algorithms/sidb_simulation.rst
  include/fiction/algorithms/iter/gray_code_iterator.hpp
  include/fiction/algorithms/simulation/sidb/can_positive_charges_occur.hpp
  include/fiction/algorithms/simulation/sidb/critical_temperature.hpp
  include/fiction/algorithms/simulation/sidb/enum_class_exhaustive_algorithm.hpp
  include/fiction/algorithms/simulation/sidb/exhaustive_ground_state_simulation.hpp
  include/fiction/algorithms/simulation/sidb/is_ground_state.hpp
  include/fiction/algorithms/simulation/sidb/maximum_defect_influence_position_and_distance.hpp
  include/fiction/algorithms/simulation/sidb/occupation_probability_of_excited_states.hpp
  include/fiction/algorithms/simulation/sidb/quickexact.hpp
  include/fiction/algorithms/simulation/sidb/quicksim.hpp
  include/fiction/algorithms/simulation/sidb/time_to_solution.hpp
  include/fiction/io/write_location_and_ground_state.hpp
  include/fiction/technology/charge_distribution_surface.hpp
  include/fiction/types.hpp
  include/fiction/utils/execution_utils.hpp
  test/algorithms/simulation/sidb/can_positive_charges_occur.cpp
  test/algorithms/simulation/sidb/critical_temperature.cpp
  test/algorithms/simulation/sidb/exhaustive_ground_state_simulation.cpp
  test/algorithms/simulation/sidb/maximum_defect_influence_position_and_distance.cpp
  test/algorithms/simulation/sidb/quickexact.cpp
  test/algorithms/simulation/sidb/time_to_solution.cpp
  test/io/write_location_and_ground_state.cpp
  test/technology/charge_distribution_surface.cpp
  test/technology/sidb_defects.cpp
Labels: enhancement

#260 ✨ Post-Layout Optimization
  cli/cmd/physical_design/optimize.hpp
  cli/commands.hpp
  docs/algorithms/algorithms.rst
  docs/algorithms/post_layout_optimization.rst
  experiments/post_layout_optimization/post_layout_optimization.cpp
  include/fiction/algorithms/physical_design/post_layout_optimization.hpp
  include/fiction/layouts/cartesian_layout.hpp
  include/fiction/layouts/cell_level_layout.hpp
  include/fiction/layouts/clocked_layout.hpp
  include/fiction/layouts/gate_level_layout.hpp
  include/fiction/layouts/hexagonal_layout.hpp
  include/fiction/layouts/shifted_cartesian_layout.hpp
  include/fiction/layouts/synchronization_element_layout.hpp
  include/fiction/layouts/tile_based_layout.hpp
  test/algorithms/physical_design/post_layout_optimization.cpp
  test/layouts/cartesian_layout.cpp
  test/layouts/cell_level_layout.cpp
  test/layouts/clocked_layout.cpp
  test/layouts/gate_level_layout.cpp
  test/layouts/hexagonal_layout.cpp
  test/layouts/shifted_cartesian_layout.cpp
  test/layouts/synchronization_element_layout.cpp
  test/utils/blueprints/layout_blueprints.hpp
Labels: enhancement

#287 :bug: Fixed a `nullptr` dereference bug
  cli/cmd/physical_design/hex.hpp
  experiments/hexagonalization/hexagonalization.cpp
  include/fiction/algorithms/physical_design/hexagonalization.hpp
  include/fiction/algorithms/physical_design/post_layout_optimization.hpp
  test/algorithms/physical_design/hexagonalization.cpp
  test/algorithms/physical_design/post_layout_optimization.cpp
Labels: bug

#283 🚨 Fix compiler warnings and more consistency
  README.md
  docs/algorithms/sidb_simulation.rst
  include/fiction/algorithms/simulation/sidb/calculate_energy_and_state_type.hpp
  include/fiction/algorithms/simulation/sidb/critical_temperature.hpp
  include/fiction/algorithms/simulation/sidb/exhaustive_ground_state_simulation.hpp
  include/fiction/algorithms/simulation/sidb/maximum_defect_influence_position_and_distance.hpp
  include/fiction/algorithms/simulation/sidb/quickexact.hpp
  include/fiction/algorithms/simulation/sidb/random_sidb_layout_generator.hpp
  include/fiction/algorithms/simulation/sidb/sidb_simulation_engine.hpp
  include/fiction/algorithms/simulation/sidb/sidb_simulation_result.hpp
  include/fiction/algorithms/simulation/sidb/time_to_solution.hpp
  include/fiction/technology/charge_distribution_surface.hpp
  test/algorithms/simulation/sidb/time_to_solution.cpp
  test/technology/charge_distribution_surface.cpp
Labels: documentation, compiler issue

#282 ✨ SiDB Gate Designer
  docs/algorithms/algorithms.rst
  docs/algorithms/design_sidb_gates.rst
  docs/algorithms/sidb_simulation.rst
  docs/utils/utils.rst
  experiments/operational_domain/operational_domain_siqad.cpp
  experiments/skeleton_bestagons_with_tags/skeleton_hex_inputsdbp_1i1o_diagonal.sqd
  experiments/skeleton_bestagons_with_tags/skeleton_hex_inputsdbp_1i1o_straight.sqd
  experiments/skeleton_bestagons_with_tags/skeleton_hex_inputsdbp_1i2o.sqd
  experiments/skeleton_bestagons_with_tags/skeleton_hex_inputsdbp_2i1o.sqd
  experiments/skeleton_bestagons_with_tags/skeleton_hex_inputsdbp_2i2o.sqd
  include/fiction/algorithms/iter/bdl_input_iterator.hpp
  include/fiction/algorithms/physical_design/design_sidb_gates.hpp
  include/fiction/algorithms/simulation/sidb/calculate_energy_and_state_type.hpp
  include/fiction/algorithms/simulation/sidb/critical_temperature.hpp
  include/fiction/algorithms/simulation/sidb/energy_distribution.hpp
  include/fiction/algorithms/simulation/sidb/is_operational.hpp
  include/fiction/algorithms/simulation/sidb/maximum_defect_influence_position_and_distance.hpp
  include/fiction/algorithms/simulation/sidb/operational_domain.hpp
  include/fiction/algorithms/simulation/sidb/quickexact.hpp
  include/fiction/algorithms/simulation/sidb/quicksim.hpp
  include/fiction/algorithms/simulation/sidb/random_sidb_layout_generator.hpp
  include/fiction/algorithms/simulation/sidb/time_to_solution.hpp
  include/fiction/io/write_operational_domain.hpp
  include/fiction/utils/layout_utils.hpp
  include/fiction/utils/math_utils.hpp
  include/fiction/utils/truth_table_utils.hpp
  test/algorithms/physical_design/design_sidb_gates.cpp
  test/algorithms/simulation/sidb/can_positive_charges_occur.cpp
  test/algorithms/simulation/sidb/critical_temperature.cpp
  test/algorithms/simulation/sidb/energy_distribution.cpp
  test/algorithms/simulation/sidb/exhaustive_ground_state_simulation.cpp
  test/algorithms/simulation/sidb/is_groundstate.cpp
  test/algorithms/simulation/sidb/is_operational.cpp
  test/algorithms/simulation/sidb/maximum_defect_influence_position_and_distance.cpp
  test/algorithms/simulation/sidb/minimum_energy.cpp
  test/algorithms/simulation/sidb/occupation_probability_of_excited_states.cpp
  test/algorithms/simulation/sidb/operational_domain.cpp
  test/algorithms/simulation/sidb/quickexact.cpp
  test/algorithms/simulation/sidb/quicksim.cpp
  test/algorithms/simulation/sidb/random_sidb_layout_generator.cpp
  test/algorithms/simulation/sidb/sidb_simulation_parameters.cpp
  test/algorithms/simulation/sidb/time_to_solution.cpp
  test/io/write_operational_domain.cpp
  test/utils/layout_utils.cpp
  test/utils/math_utils.cpp
Labels: enhancement

#292 🐛 Fix docstring generator
  .github/workflows/pyfiction-docstring-generator.yml
Labels: bug

#293 ✨ Add post layout optimization to pyfiction and update docstrings
  bindings/pyfiction/include/pyfiction/algorithms/physical_design/post_layout_optimization.hpp
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/pyfiction/pyfiction.cpp
  bindings/pyfiction/test/algorithms/physical_design/test_post_layout_optimization.py
  docs/algorithms/post_layout_optimization.rst
Labels: enhancement

#295 ✨ Add hexagonalization algorithm to pyfiction
  bindings/pyfiction/include/pyfiction/algorithms/physical_design/hexagonalization.hpp
  bindings/pyfiction/include/pyfiction/layouts/cell_level_layout.hpp
  bindings/pyfiction/include/pyfiction/types.hpp
  bindings/pyfiction/pyfiction.cpp
  bindings/pyfiction/test/algorithms/physical_design/test_hexagonalization.py
  docs/algorithms/hexagonalization.rst
Labels: enhancement

#289 :sparkles: Support defects in the SiDB Gate Designer
  include/fiction/algorithms/physical_design/design_sidb_gates.hpp
  include/fiction/algorithms/simulation/sidb/random_sidb_layout_generator.hpp
  include/fiction/technology/sidb_surface.hpp
  test/algorithms/physical_design/design_sidb_gates.cpp
  test/algorithms/simulation/sidb/random_sidb_layout_generator.cpp
Labels: enhancement
