Repository cda-tum/fiction, pull requests merged in 2023-10, with the labels that each got.

#302 :wrench: Update the Doxygen documentation system
  .readthedocs.yml
  docs/Doxyfile
  docs/conf.py
  docs/requirements.txt
Labels: documentation

#304 :memo: Updated README to make it more approachable
  README.md
Labels: documentation

#303 🔧 Fix broken CodeQL Pipeline
  .github/workflows/codeql-analysis.yml
Labels: bug, github_actions

#301 :wrench: Updated the linguist attributes
  .gitattributes
  .lgtm.yml
Labels: documentation, small fix

#300 :wrench: Update Dependabot to enable grouped pull requests
  .github/dependabot.yml
Labels: github_actions

#306 :art: Fix minor oversights by using `static constexpr` and `noexcept`
  include/fiction/layouts/clocking_scheme.hpp
  include/fiction/utils/stl_utils.hpp
Labels: small fix, performance

#296 ✨ Gate-level layout file reader and writer
  cli/cmd/io/fgl.hpp
  cli/cmd/io/read.hpp
  cli/commands.hpp
  docs/io/input.rst
  docs/io/physical_simulation.rst
  include/fiction/io/read_fgl_layout.hpp
  include/fiction/io/write_fgl_layout.hpp
  test/io/read_fgl_layout.cpp
  test/io/write_fgl_layout.cpp
  test/utils/blueprints/layout_blueprints.hpp
Labels: enhancement, cli

#309 :bug: Fixed design-rule violation testing and equivalence checking on empty gate-level layouts
  include/fiction/algorithms/verification/design_rule_violations.hpp
  test/algorithms/verification/design_rule_violations.cpp
  test/algorithms/verification/equivalence_checking.cpp
Labels: bug

#308 ✨ Expose gate-level layout reader and writer
  bindings/pyfiction/include/pyfiction/io/read_fgl_layout.hpp
  bindings/pyfiction/include/pyfiction/io/write_fgl_layout.hpp
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/pyfiction/pyfiction.cpp
  bindings/pyfiction/test/io/__init__.py
  bindings/pyfiction/test/io/test_read_write_fgl_layout.py
  docs/io/input.rst
  docs/io/physical_simulation.rst
Labels: enhancement

#311 ✨ Add naming utils to logic network
  bindings/pyfiction/include/pyfiction/networks/logic_network.hpp
  bindings/pyfiction/test/networks/test_logic_network.py
Labels: enhancement

#310 🎨 support cds as input for all simulators
  docs/algorithms/sidb_simulation.rst
  include/fiction/algorithms/simulation/sidb/can_positive_charges_occur.hpp
  include/fiction/algorithms/simulation/sidb/exhaustive_ground_state_simulation.hpp
  include/fiction/algorithms/simulation/sidb/quickexact.hpp
  include/fiction/algorithms/simulation/sidb/quicksim.hpp
  include/fiction/technology/charge_distribution_surface.hpp
  include/fiction/traits.hpp
  test/algorithms/simulation/sidb/critical_temperature.cpp
  test/algorithms/simulation/sidb/exhaustive_ground_state_simulation.cpp
  test/algorithms/simulation/sidb/quickexact.cpp
  test/algorithms/simulation/sidb/quicksim.cpp
  test/algorithms/simulation/sidb/time_to_solution.cpp
  test/technology/charge_distribution_surface.cpp
Labels: enhancement

#316 ✨Refactored the hexagonalization algorithm
  docs/algorithms/hexagonalization.rst
  experiments/hexagonalization/hexagonalization.cpp
  include/fiction/algorithms/physical_design/hexagonalization.hpp
  test/algorithms/physical_design/hexagonalization.cpp
Labels: enhancement

#320 :green_heart: Fix VSC builds
  CMakeLists.txt
  cmake/Utilities.cmake
  cmake/VCEnvironment.cmake
Labels: bug
