Repository cda-tum/fiction, pull requests merged in 2023-12, with the labels that each got.

#352 :green_heart: Hotfix for the macOS CI
  .github/workflows/macos.yml
Labels: github_actions, small fix

#353 :green_heart: Fix for MacOS CI
  .github/workflows/macos.yml
Labels: bug

#354 🐛 Atomic defect can be updated or new one can be assigned at specific coordinate.
  include/fiction/technology/sidb_surface.hpp
  test/technology/sidb_surface.cpp
Labels: bug

#355 :bug: `read_sqd_layout` now updates the aspect ratio properly for SiQAD-coordinate based layouts
  include/fiction/io/read_sqd_layout.hpp
  test/io/read_sqd_layout.cpp
Labels: bug

#349 :sparkles: Compile time flows and CLI simulation update
  cli/CMakeLists.txt
  cli/cmd/io/read.hpp
  cli/cmd/simulation/opdom.hpp
  cli/cmd/simulation/quickexact.hpp
  cli/cmd/simulation/quicksim.hpp
  cli/cmd/simulation/temp.hpp
  cli/commands.hpp
  cli/stores.hpp
  cmake/PackageProject.cmake
  docs/algorithms/sidb_simulation.rst
  docs/cli.rst
  include/fiction/algorithms/simulation/sidb/critical_temperature.hpp
  include/fiction/algorithms/simulation/sidb/is_ground_state.hpp
  include/fiction/algorithms/simulation/sidb/maximum_defect_influence_position_and_distance.hpp
  include/fiction/algorithms/simulation/sidb/minimum_energy.hpp
  include/fiction/algorithms/simulation/sidb/operational_domain.hpp
  include/fiction/algorithms/simulation/sidb/quickexact.hpp
  include/fiction/algorithms/simulation/sidb/quicksim.hpp
  include/fiction/algorithms/simulation/sidb/sidb_simulation_result.hpp
  include/fiction/algorithms/simulation/sidb/time_to_solution.hpp
  include/fiction/io/print_layout.hpp
  include/fiction/io/write_location_and_ground_state.hpp
  include/fiction/io/write_operational_domain.hpp
  include/fiction/layouts/cell_level_layout.hpp
  include/fiction/technology/charge_distribution_surface.hpp
  include/fiction/types.hpp
  include/fiction/utils/layout_utils.hpp
  test/algorithms/simulation/sidb/can_positive_charges_occur.cpp
  test/algorithms/simulation/sidb/critical_temperature.cpp
  test/algorithms/simulation/sidb/minimum_energy.cpp
  test/algorithms/simulation/sidb/quickexact.cpp
  test/algorithms/simulation/sidb/quicksim.cpp
  test/io/write_sqd_sim_result.cpp
Labels: enhancement, cli

#359 :memo: Added an SiDB simulation figure to the README
  README.md
  docs/_static/sidb_simulation.png
Labels: enhancement, documentation

#358 :sparkles: Added 'Ripple' to the list of supported clocking schemes
  README.md
  cli/cmd/physical_design/exact.hpp
  docs/_static/ripple.png
  docs/_static/ripple.svg
  docs/layouts/clocking_scheme.rst
  include/fiction/layouts/clocking_scheme.hpp
  test/layouts/clocking_scheme.cpp
Labels: enhancement

#360 :sparkles: Added an upper bound option for the total layout area to `exact`
  cli/cmd/physical_design/exact.hpp
  include/fiction/algorithms/physical_design/exact.hpp
  test/algorithms/physical_design/exact.cpp
Labels: enhancement, cli
