Repository cda-tum/fiction, pull requests merged in 2023-03, with the labels that each got.

#125 :sparkles: Added conversion functions for layouts of different coordinate types
  docs/utils/utils.rst
  include/fiction/traits.hpp
  include/fiction/utils/layout_utils.hpp
  test/utils/layout_utils.cpp
Labels: enhancement

#132 :construction_worker: Updates to the CI platform
  .github/codeql-config.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/coverage.yml
  .github/workflows/docker-image.yml
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
  include/fiction/io/write_sqd_layout.hpp
Labels: enhancement, github_actions

#133 :memo: Added GitHub templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/contributing.rst
  .github/pull_request_template.md
  .github/support.rst
Labels: enhancement, documentation

#134 :bug: Fixed accessing non-existing variables in `potential_between_sidbs`
  include/fiction/technology/charge_distribution_surface.hpp
Labels: bug

#135 :adhesive_bandage: Renamed functions to more appropriately reflect their role
  include/fiction/technology/charge_distribution_surface.hpp
  test/technology/charge_distribution_surface.cpp
Labels: small fix, test

#141 :construction_worker: Changed CI name
  .github/workflows/clang-format.yml
  .github/workflows/clang-tidy-review.yml
Labels: github_actions, small fix

#139 :sparkles: Release Drafter to automatically maintain a Draft Release
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: enhancement, github_actions, documentation

#142 :art: CI inconsistency fixes
  .github/release-drafter.yml
  .github/workflows/clang-tidy-review-post.yml
  .github/workflows/release-drafter.yml
Labels: github_actions, small fix

#138 :art: added a new function ``get_chargeless_potential_between_sidbs``
  include/fiction/technology/charge_distribution_surface.hpp
  test/technology/charge_distribution_surface.cpp
Labels: enhancement, small fix

#136 :white_check_mark: Added unit tests for ExGS and QuickSim
  include/fiction/algorithms/simulation/sidb/quicksim.hpp
  test/algorithms/simulation/sidb/exhaustive_ground_state_simulation.cpp
  test/algorithms/simulation/sidb/quicksim.cpp
Labels: test

#144 :memo: Updated the list of implemented design automation algorithms
  README.md
  docs/algorithms/sidb_simulation.rst
  docs/publications.rst
  include/fiction/algorithms/simulation/sidb/quicksim.hpp
Labels: documentation

#149 :memo: Updated notes on the installation process to the documentation
  docs/getting_started.rst
Labels: documentation, small fix

#152 :memo: Fixed namespace in SiQAD utility function documentation
  docs/layouts/coordinates.rst
Labels: bug, documentation

#151 :rotating_light: Fixed warnings and notes brought up by CodeQL
  .github/codeql-config.yml
  include/fiction/algorithms/physical_design/exact.hpp
  include/fiction/algorithms/physical_design/one_pass_synthesis.hpp
  include/fiction/algorithms/simulation/sidb/quicksim.hpp
  include/fiction/layouts/bounding_box.hpp
  test/algorithms/network_transformation/network_conversion.cpp
  test/algorithms/path_finding/distance.cpp
  test/algorithms/simulation/sidb/minimum_energy.cpp
  test/algorithms/simulation/sidb/time_to_solution.cpp
  test/technology/charge_distribution_surface.cpp
Labels: small fix

#153 :zap: Utilize `std::string_view` instead of `std::string` in many places to improve performance
  experiments/color_routing/color_routing.cpp
  include/fiction/io/csv_writer.hpp
  include/fiction/io/dot_drawers.hpp
  include/fiction/io/network_reader.hpp
  include/fiction/io/read_fqca_layout.hpp
  include/fiction/io/read_sidb_surface_defects.hpp
  include/fiction/io/write_qcc_layout.hpp
  include/fiction/layouts/cell_level_layout.hpp
  include/fiction/layouts/clocking_scheme.hpp
Labels: performance

#154 :rotating_light: Fixes for linker errors and CMake name collisions
  CMakeLists.txt
  cli/CMakeLists.txt
  include/fiction/technology/sidb_charge_state.hpp
  test/CMakeLists.txt
Labels: bug, small fix, compiler issue

#157 🚨 Fixed error message from multiple IPO Checks
  cmake/StandardProjectSettings.cmake
Labels: bug, compiler issue

#166 :construction_worker: Updated compilers on GitHub Actions to match latest runner versions
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
Labels: github_actions

#162 :bug: Removed excess template parameter `typename T`
  include/fiction/utils/name_utils.hpp
Labels: bug, small fix

#167 :memo: Fixed some inconcistencies in the RTD documentation
  docs/algorithms/sidb_simulation.rst
  docs/cli.rst
  docs/conf.py
  docs/getting_started.rst
  docs/index.rst
  docs/layouts/obstruction_layout.rst
  docs/technology/defects.rst
  docs/technology/simulation.rst
  include/fiction/algorithms/iter/aspect_ratio_iterator.hpp
  include/fiction/algorithms/verification/equivalence_checking.hpp
Labels: documentation, small fix

#169 :memo: Update the CHANGELOG to include the latest changes
  .github/release-drafter.yml
  docs/changelog.rst
Labels: documentation

#168 :art: Restructured `sidb_charge_state` and added tests
  include/fiction/technology/sidb_charge_state.hpp
  test/technology/sidb_charge_state.cpp
Labels: test

#172 :sparkles: New SiDB simulator *QuickExact* and simulation of atomic defects
  experiments/tts_acc_all_bestagon.cpp
  include/fiction/algorithms/simulation/sidb/exhaustive_ground_state_simulation.hpp
  include/fiction/algorithms/simulation/sidb/quicksim.hpp
  include/fiction/algorithms/simulation/sidb/time_to_solution.hpp
  include/fiction/technology/charge_distribution_surface.hpp
  test/algorithms/simulation/sidb/exhaustive_ground_state_simulation.cpp
  test/algorithms/simulation/sidb/time_to_solution.cpp
  test/technology/charge_distribution_surface.cpp
Labels: enhancement
