Repository cda-tum/fiction, pull requests merged in 2023-02, with the labels that each got.

#105 Added a framework for accurate and efficient simulation of SiDB logic
  docs/index.rst
  docs/layouts/coordinates.rst
  docs/technology/simulation.rst
  experiments/defect_aware_physical_design/generate_defective_surface.py
  include/fiction/algorithms/path_finding/distance.hpp
  include/fiction/algorithms/simulation/sidb/energy_distribution.hpp
  include/fiction/algorithms/simulation/sidb/exhaustive_ground_state_simulation.hpp
  include/fiction/algorithms/simulation/sidb/is_groundstate.hpp
  include/fiction/algorithms/simulation/sidb/minimum_energy.hpp
  include/fiction/algorithms/simulation/sidb/quicksim.hpp
  include/fiction/algorithms/simulation/sidb/sidb_simulation_parameters.hpp
  include/fiction/algorithms/simulation/sidb/time_to_solution.hpp
  include/fiction/io/read_sqd_layout.hpp
  include/fiction/layouts/coordinates.hpp
  include/fiction/technology/charge_distribution_surface.hpp
  include/fiction/technology/physical_constants.hpp
  include/fiction/technology/sidb_bestagon_library.hpp
  include/fiction/technology/sidb_charge_state.hpp
  include/fiction/technology/sidb_nm_position.hpp
  include/fiction/traits.hpp
  include/fiction/types.hpp
  test/algorithms/path_finding/distance.cpp
  test/algorithms/simulation/sidb/energy_distribution.cpp
  test/algorithms/simulation/sidb/exhaustive_ground_state_simulation.cpp
  test/algorithms/simulation/sidb/is_groundstate.cpp
  test/algorithms/simulation/sidb/minimum_energy.cpp
  test/algorithms/simulation/sidb/quicksim.cpp
  test/algorithms/simulation/sidb/time_to_solution.cpp
  test/layouts/coordinates.cpp
  test/technology/charge_distribution_surface.cpp
Labels: enhancement

#109 :memo: Added RST documentation for the SiDB simulation framework
  docs/algorithms/algorithms.rst
  docs/algorithms/sidb_simulation.rst
  docs/technology/simulation.rst
  include/fiction/algorithms/simulation/sidb/energy_distribution.hpp
  include/fiction/algorithms/simulation/sidb/exhaustive_ground_state_simulation.hpp
  include/fiction/algorithms/simulation/sidb/is_ground_state.hpp
  include/fiction/algorithms/simulation/sidb/minimum_energy.hpp
  include/fiction/algorithms/simulation/sidb/quicksim.hpp
  include/fiction/algorithms/simulation/sidb/time_to_solution.hpp
  test/algorithms/simulation/sidb/is_groundstate.cpp
Labels: documentation

#110 :bug: Fixed duplicate crossing cells in the iNML technology
  include/fiction/algorithms/physical_design/apply_gate_library.hpp
  include/fiction/technology/inml_topolinano_library.hpp
Labels: bug

#111 :bug: Fixed several I/O issues
  cli/cmd/io/blif.hpp
  cli/cmd/io/fqca.hpp
  cli/cmd/io/qca.hpp
  cli/cmd/io/qcc.hpp
  cli/cmd/io/qll.hpp
  cli/cmd/io/sqd.hpp
  include/fiction/io/print_layout.hpp
  include/fiction/types.hpp
  test/io/print_layout.cpp
Labels: bug

#113 :bug: Fixed a bug in `color_routing`
  include/fiction/algorithms/graph/generate_edge_intersection_graph.hpp
  test/algorithms/physical_design/color_routing.cpp
Labels: bug

#115 :sparkles: Added a Verilog writer to the CLI
  cli/cmd/io/verilog.hpp
  cli/commands.hpp
Labels: enhancement, cli

#112 :fire: Removed unnecessary Catch2 CMake call
  test/CMakeLists.txt
Labels: small fix

#114 :art: Fixed a few inconsistencies
  include/fiction/algorithms/verification/design_rule_violations.hpp
Labels: small fix

#117 :bug: Added additional checks for `is_obstructed_connection` to ensure proper handling of crossing cases
  include/fiction/layouts/cartesian_layout.hpp
  include/fiction/layouts/obstruction_layout.hpp
  test/algorithms/physical_design/color_routing.cpp
  test/layouts/obstruction_layout.cpp
Labels: bug

#118 :zap: Improved performance by switching to `phmap` in more places
  include/fiction/algorithms/graph/generate_edge_intersection_graph.hpp
  include/fiction/algorithms/path_finding/enumerate_all_paths.hpp
  include/fiction/algorithms/path_finding/k_shortest_paths.hpp
Labels: performance

#119 :white_check_mark: Added tests for STL utils
  include/fiction/utils/stl_utils.hpp
  test/utils/stl_utils.cpp
Labels: test

#122 :bug: Fixed a bug in crossing considerations of `obstruction_layout`s
  include/fiction/algorithms/path_finding/a_star.hpp
  include/fiction/layouts/obstruction_layout.hpp
Labels: bug

#123 :art: Small inconsistency fix
  include/fiction/algorithms/simulation/sidb/sidb_simulation_parameters.hpp
  include/fiction/technology/sidb_nm_position.hpp
Labels: small fix

#127 :memo: Revised the README badges
  README.md
Labels: enhancement, documentation

#128 :sparkles: Added multi-threading support for QuickSim
  include/fiction/algorithms/simulation/sidb/is_ground_state.hpp
  include/fiction/algorithms/simulation/sidb/quicksim.hpp
  include/fiction/algorithms/simulation/sidb/time_to_solution.hpp
  include/fiction/technology/charge_distribution_surface.hpp
  test/algorithms/simulation/sidb/quicksim.cpp
Labels: enhancement, performance
