Repository cda-tum/fiction, pull requests merged in 2023-05, with the labels that each got.

#197 :art: Ensured SiQAD compatibility of SiDB simulation result writer
  include/fiction/io/write_sqd_sim_result.hpp
  test/io/write_sqd_sim_result.cpp
Labels: small fix

#205 :bug: Specify build OS in readthedocs
  .readthedocs.yml
Labels: small fix

#204 ✨ Add gate checks to pyfiction
  bindings/pyfiction/include/pyfiction/layouts/gate_level_layout.hpp
  bindings/pyfiction/test/layouts/test_gate_level_layout.py
Labels: enhancement

#208 :green_heart: Fixed the Docker CI by installing Z3 via `pip`
  .github/workflows/docker-image.yml
  Dockerfile
Labels: bug, github_actions

#120 :sparkles: Temperature-aware physical SiDB simulation
  docs/algorithms/sidb_simulation.rst
  include/fiction/algorithms/simulation/sidb/calculate_energy_and_state_type.hpp
  include/fiction/algorithms/simulation/sidb/critical_temperature.hpp
  include/fiction/algorithms/simulation/sidb/energy_distribution.hpp
  include/fiction/algorithms/simulation/sidb/exhaustive_ground_state_simulation.hpp
  include/fiction/algorithms/simulation/sidb/is_ground_state.hpp
  include/fiction/algorithms/simulation/sidb/minimum_energy.hpp
  include/fiction/algorithms/simulation/sidb/occupation_probability_of_excited_states.hpp
  include/fiction/algorithms/simulation/sidb/quicksim.hpp
  include/fiction/algorithms/simulation/sidb/sidb_simulation_result.hpp
  include/fiction/algorithms/simulation/sidb/time_to_solution.hpp
  include/fiction/io/write_sqd_sim_result.hpp
  include/fiction/layouts/coordinates.hpp
  include/fiction/technology/charge_distribution_surface.hpp
  include/fiction/utils/truth_table_utils.hpp
  test/algorithms/simulation/sidb/critical_temperature.cpp
  test/algorithms/simulation/sidb/exhaustive_ground_state_simulation.cpp
  test/algorithms/simulation/sidb/is_groundstate.cpp
  test/algorithms/simulation/sidb/occupation_probability_of_excited_states.cpp
  test/algorithms/simulation/sidb/quicksim.cpp
  test/io/write_sqd_sim_result.cpp
Labels: enhancement

#210 :zap: Use `mold` instead of `ld` for faster link times
  .github/workflows/codeql-analysis.yml
  .github/workflows/coverage.yml
  .github/workflows/ubuntu.yml
  Dockerfile
Labels: github_actions, performance

#211 :bug: Wrong position of output wire
  include/fiction/technology/sidb_bestagon_library.hpp
Labels: bug

#215 :bento: Added the MNT logo to the README and RtD
  LICENSE.txt
  README.md
  docs/_static/mnt_dark.svg
  docs/_static/mnt_light.svg
  docs/_static/mnt_sidebar.svg
  docs/conf.py
Labels: documentation

#222 :bug: Fixed an issue with `charge_distribution_surface` not being recognized as a `cell_level_layout`
  include/fiction/traits.hpp
  test/technology/charge_distribution_surface.cpp
Labels: bug

#220 :memo: Add paper references to functions
  docs/algorithms/sidb_simulation.rst
  docs/publications.rst
  include/fiction/algorithms/simulation/sidb/critical_temperature.hpp
  include/fiction/algorithms/simulation/sidb/quicksim.hpp
Labels: documentation

#224 🐛 Fixed wrong SiDB locations in a Bestagon tile's input wire
  include/fiction/technology/sidb_bestagon_library.hpp
Labels: bug
