Repository cda-tum/fiction, pull requests merged in 2024-10, with the labels that each got.

#529 ✨ Multithreading support for `gold`
  bindings/pyfiction/include/pyfiction/algorithms/physical_design/graph_oriented_layout_design.hpp
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/pyfiction/test/algorithms/physical_design/test_graph_oriented_layout_design.py
  cli/cmd/physical_design/gold.hpp
  include/fiction/algorithms/physical_design/graph_oriented_layout_design.hpp
  test/algorithms/physical_design/graph_oriented_layout_design.cpp
  test/benchmark/graph_oriented_layout_design.cpp
  test/utils/blueprints/network_blueprints.hpp
Labels: enhancement

#536 :memo: Fix duplicated CHANGELOG entry
  docs/changelog.rst
Labels: documentation, small fix

#537 :memo: Added a `CITATION.cff` file
  CITATION.cff
Labels: documentation

#548 📝 Update the `CHANGELOG`
  docs/changelog.rst
Labels: documentation

#549 :bookmark: Bump version to 0.6.5
  CITATION.cff
  CMakeLists.txt
  docs/changelog.rst
  docs/conf.py
  pyproject.toml
  setup.py
Labels: versioning

#551 🐛 Fix neutral defect handling in CDS and correct gate design termination condition.
  include/fiction/algorithms/physical_design/design_sidb_gates.hpp
  include/fiction/technology/charge_distribution_surface.hpp
  test/algorithms/physical_design/design_sidb_gates.cpp
  test/technology/charge_distribution_surface.cpp
Labels: bug

#554 :inbox_tray: Add Bestagon SiDB gate library
  experiments/bestagon_gates_type_tags/and/21_hex_inputsdbp_and_v19.sqd
  experiments/bestagon_gates_type_tags/cx/22_hex_inputsdbp_cx_try2_v0.sqd
  experiments/bestagon_gates_type_tags/fo2/12_hex_inputsdbp_fo2_v6.sqd
  experiments/bestagon_gates_type_tags/ha/22_hex_inputsdbp_ha_v2.sqd
  experiments/bestagon_gates_type_tags/hourglass/22_hex_inputsdbp_hourglass_v0.sqd
  experiments/bestagon_gates_type_tags/inv/hex_11_inputsdbp_inv_straight_v0_manual.sqd
  experiments/bestagon_gates_type_tags/inv_diag/hex_11_inputsdbp_inv_diag_v0_manual.sqd
  experiments/bestagon_gates_type_tags/nand/21_hex_inputsdbp_nand_v7.sqd
  experiments/bestagon_gates_type_tags/nor/21_hex_inputsdbp_nor_v7.sqd
  experiments/bestagon_gates_type_tags/or/21_hex_inputsdbp_or_v17.sqd
  experiments/bestagon_gates_type_tags/wire/hex_11_inputsdbp_wire_straight_v0_manual.sqd
  experiments/bestagon_gates_type_tags/wire_diag/hex_11_inputsdbp_wire_diag_v0_manual.sqd
  experiments/bestagon_gates_type_tags/xnor/hex_21_inputsdbp_xnor_v21.sqd
  experiments/bestagon_gates_type_tags/xor/hex_21_inputsdbp_xor_v1.sqd
Labels: enhancement

#556 :memo: Fix documentation for BDL wire detection
  bindings/pyfiction/include/pyfiction/algorithms/simulation/sidb/detect_bdl_wires.hpp
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  docs/algorithms/sidb_simulation.rst
  include/fiction/algorithms/simulation/sidb/detect_bdl_wires.hpp
Labels: documentation, small fix

#557 :snake: Support Python 3.13
  .github/workflows/codeql-analysis.yml
  .github/workflows/coverage.yml
  .github/workflows/macos.yml
  .github/workflows/pyfiction-docstring-generator.yml
  .github/workflows/pyfiction-pypi-deployment.yml
  .github/workflows/python-bindings.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
Labels: github_actions, python
