Repository cda-tum/fiction, pull requests merged in 2024-05, with the labels that each got.

#427 :art: Consistency fixes for `pyfiction` and the documentation
  .github/workflows/clang-tidy-review.yml
  .github/workflows/pyfiction-docstring-generator.yml
  .github/workflows/python-bindings.yml
  README.md
  bindings/pyfiction/README.md
  bindings/pyfiction/include/pyfiction/technology/charge_distribution_surface.hpp
  bindings/pyfiction/include/pyfiction/technology/sidb_lattice.hpp
  bindings/pyfiction/pyfiction.cpp
  bindings/pyfiction/test/algorithms/simulation/sidb/test_assess_physical_population_stability.py
  bindings/pyfiction/test/algorithms/simulation/sidb/test_can_positive_charges_occur.py
  bindings/pyfiction/test/algorithms/simulation/sidb/test_check_simulation_results_for_equivalence.py
  bindings/pyfiction/test/algorithms/simulation/sidb/test_critical_temperature.py
  bindings/pyfiction/test/algorithms/simulation/sidb/test_detect_bdl_pairs.py
  bindings/pyfiction/test/algorithms/simulation/sidb/test_determine_groundstate_from_simulation_results.py
  bindings/pyfiction/test/algorithms/simulation/sidb/test_exhaustive_ground_state_simulation.py
  bindings/pyfiction/test/algorithms/simulation/sidb/test_is_ground_state.py
  bindings/pyfiction/test/algorithms/simulation/sidb/test_is_operational.py
  bindings/pyfiction/test/algorithms/simulation/sidb/test_minimum_energy.py
  bindings/pyfiction/test/algorithms/simulation/sidb/test_quickexact.py
  bindings/pyfiction/test/algorithms/simulation/sidb/test_quicksim.py
  bindings/pyfiction/test/algorithms/simulation/sidb/test_random_sidb_layout_generator.py
  bindings/pyfiction/test/algorithms/simulation/sidb/test_sidb_simulation_result.py
  bindings/pyfiction/test/algorithms/simulation/sidb/test_time_to_solution.py
  bindings/pyfiction/test/technology/test_charge_distribution_surface.py
  bindings/pyfiction/test/technology/test_sidb_lattice.py
  bindings/pyfiction/test/technology/test_sidb_nm_distance.py
  bindings/pyfiction/test/technology/test_sidb_nm_position.py
  cmake/CompilerWarnings.cmake
  docs/getting_started.rst
  docs/index.rst
  docs/technology/hsi_lattices.rst
  docs/technology/sidb_lattice.rst
  docs/technology/sidb_lattice_orientations.rst
  docs/technology/simulation.rst
  include/fiction/algorithms/physical_design/hexagonalization.hpp
  include/fiction/algorithms/physical_design/post_layout_optimization.hpp
  include/fiction/algorithms/physical_design/wiring_reduction.hpp
  include/fiction/algorithms/simulation/sidb/operational_domain.hpp
  include/fiction/layouts/cell_level_layout.hpp
  include/fiction/types.hpp
  include/fiction/utils/layout_utils.hpp
Labels: documentation, small fix, python

#428 :bookmark: When it comes to the past, everyone writes fiction
  .github/pull_request_template.md
  CMakeLists.txt
  docs/changelog.rst
  docs/conf.py
  pyproject.toml
  setup.py
Labels: versioning

#430 :sparkles: Added truth table helpers for 3-input functions
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/pyfiction/include/pyfiction/utils/truth_table_utils.hpp
  docs/utils/utils.rst
  include/fiction/utils/truth_table_utils.hpp
Labels: enhancement

#431 🐛 PyPI Deployment for multiple operating systems
  .github/workflows/pyfiction-pypi-deployment.yml
Labels: bug

#436 👷 Limit triggering of the pyfiction deployment CI
  .github/workflows/pyfiction-pypi-deployment.yml
Labels: github_actions

#434 📝 Added more physical design algorithms to the README
  README.md
Labels: documentation

#433 🎨 Added emojis to CI/CD
  .github/workflows/clang-tidy-review-post.yml
  .github/workflows/clang-tidy-review.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/coverage.yml
  .github/workflows/docker-image.yml
  .github/workflows/macos.yml
  .github/workflows/pyfiction-docstring-generator.yml
  .github/workflows/pyfiction-pypi-deployment.yml
  .github/workflows/python-bindings.yml
  .github/workflows/release-drafter.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
Labels: github_actions

#440 🐛 Images on PyPI
  README.md
Labels: bug, documentation, small fix

#437 :bookmark: Version bump to 0.6.1
  CMakeLists.txt
  docs/changelog.rst
  docs/conf.py
  pyproject.toml
  setup.py
Labels: versioning

#441 :alembic: Added a runtime experiment script.
  experiments/sidb_simulation/runtime_analysis.cpp
  include/fiction/algorithms/simulation/sidb/time_to_solution.hpp
Labels: enhancement

#442 :snake: Minor fixes and change of template parameter of BDL pairs.
  bindings/pyfiction/include/pyfiction/algorithms/physical_design/design_sidb_gates.hpp
  bindings/pyfiction/include/pyfiction/algorithms/simulation/sidb/critical_temperature.hpp
  bindings/pyfiction/include/pyfiction/algorithms/simulation/sidb/detect_bdl_pairs.hpp
  bindings/pyfiction/test/algorithms/physical_design/test_design_sidb_gates.py
  bindings/pyfiction/test/algorithms/simulation/sidb/test_critical_temperature.py
  bindings/pyfiction/test/algorithms/simulation/sidb/test_detect_bdl_pairs.py
  docs/algorithms/sidb_simulation.rst
  docs/io/physical_simulation.rst
  include/fiction/algorithms/iter/bdl_input_iterator.hpp
  include/fiction/algorithms/physical_design/design_sidb_gates.hpp
  include/fiction/algorithms/simulation/sidb/calculate_energy_and_state_type.hpp
  include/fiction/algorithms/simulation/sidb/detect_bdl_pairs.hpp
  include/fiction/algorithms/simulation/sidb/is_operational.hpp
  include/fiction/algorithms/simulation/sidb/operational_domain.hpp
  test/algorithms/physical_design/design_sidb_gates.cpp
Labels: enhancement

#443 :bookmark: Bump version to 0.6.2
  CMakeLists.txt
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  docs/changelog.rst
  docs/conf.py
  pyproject.toml
  setup.py
Labels: versioning

#444 📝 Update hexagonalization image
  docs/_static/hexagonalization.svg
Labels: documentation
