Repository cda-tum/fiction, pull requests merged in 2024-08, with the labels that each got.

#490 :green_heart: Added Python Setup to CI Workflow
  .github/workflows/macos.yml
  .github/workflows/windows.yml
Labels: github_actions

#492 💚 Update python version for sphinx-doc
  .readthedocs.yml
Labels: github_actions

#416 ✨ Displacement Robustness Domain Simulation
  bindings/pyfiction/include/pyfiction/algorithms/simulation/sidb/displacement_robustness_domain.hpp
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/pyfiction/pyfiction.cpp
  bindings/pyfiction/test/algorithms/simulation/sidb/test_displacement_robustness_domain.py
  docs/algorithms/sidb_simulation.rst
  include/fiction/algorithms/simulation/sidb/displacement_robustness_domain.hpp
  include/fiction/algorithms/simulation/sidb/operational_domain.hpp
  include/fiction/algorithms/simulation/sidb/quickexact.hpp
  include/fiction/layouts/coordinates.hpp
  include/fiction/utils/layout_utils.hpp
  test/algorithms/simulation/sidb/displacement_robustness_domain.cpp
  test/utils/blueprints/layout_blueprints.hpp
Labels: enhancement

#456 ✨ Graph-Oriented Layout Design (GOLD)
  bindings/pyfiction/include/pyfiction/algorithms/physical_design/graph_oriented_layout_design.hpp
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/pyfiction/pyfiction.cpp
  bindings/pyfiction/test/algorithms/physical_design/test_graph_oriented_layout_design.py
  cli/cmd/physical_design/exact.hpp
  cli/cmd/physical_design/gold.hpp
  cli/cmd/physical_design/optimize.hpp
  cli/commands.hpp
  docs/algorithms/algorithms.rst
  docs/algorithms/graph_oriented_layout_design.rst
  experiments/graph_oriented_layout_design/graph_oriented_layout_design.cpp
  include/fiction/algorithms/physical_design/exact.hpp
  include/fiction/algorithms/physical_design/graph_oriented_layout_design.hpp
  include/fiction/algorithms/physical_design/orthogonal.hpp
  test/algorithms/physical_design/graph_oriented_layout_design.cpp
  test/benchmark/graph_oriented_layout_design.cpp
Labels: enhancement

#496 :sparkles: Planar Post-Layout Optimization
  bindings/pyfiction/include/pyfiction/algorithms/physical_design/post_layout_optimization.hpp
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  cli/cmd/physical_design/optimize.hpp
  include/fiction/algorithms/physical_design/post_layout_optimization.hpp
  test/algorithms/physical_design/post_layout_optimization.cpp
  test/utils/blueprints/layout_blueprints.hpp
Labels: enhancement

#497 ✨ Planar Graph-Oriented Layout Design
  bindings/pyfiction/include/pyfiction/algorithms/physical_design/graph_oriented_layout_design.hpp
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  cli/cmd/physical_design/gold.hpp
  include/fiction/algorithms/physical_design/graph_oriented_layout_design.hpp
  test/algorithms/physical_design/graph_oriented_layout_design.cpp
Labels: enhancement

#498 :arrow_up: Upgrade Z3 to Version 4.13.0 in CLI Workflow and Docker.
  .github/workflows/codeql-analysis.yml
  .github/workflows/coverage.yml
  .github/workflows/macos.yml
  .github/workflows/pyfiction-pypi-deployment.yml
  .github/workflows/python-bindings.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
  Dockerfile
Labels: github_actions

#499 :construction_worker: Update GCC versions on macOS CIs
  .github/workflows/macos.yml
  bindings/pyfiction/include/pyfiction/layouts/cell_level_layout.hpp
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/pyfiction/include/pyfiction/technology/charge_distribution_surface.hpp
  bindings/pyfiction/include/pyfiction/utils/layout_utils.hpp
  docs/utils/utils.rst
  include/fiction/io/print_layout.hpp
  include/fiction/utils/layout_utils.hpp
  test/algorithms/iter/bdl_input_iterator.cpp
  test/algorithms/physical_design/design_sidb_gates.cpp
  test/algorithms/simulation/sidb/displacement_robustness_domain.cpp
  test/io/print_layout.cpp
  test/utils/layout_utils.cpp
Labels: github_actions

#466 :construction_worker: Updated the Ubuntu CI to include 24.04 and newer compiler versions
  .github/workflows/ubuntu.yml
Labels: github_actions

#317 ✨ Defect-aware on-the-fly SiDB circuit designer
  bindings/pyfiction/include/pyfiction/algorithms/network_transformation/fanout_substitution.hpp
  bindings/pyfiction/include/pyfiction/algorithms/network_transformation/technology_mapping.hpp
  bindings/pyfiction/include/pyfiction/layouts/cartesian_layout.hpp
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/pyfiction/include/pyfiction/technology/sidb_defects.hpp
  cli/cmd/logic/map.hpp
  docs/algorithms/algorithms.rst
  docs/algorithms/apply_gate_library.rst
  docs/algorithms/on_the_fly_circuit_design_on_defective_surface.rst
  docs/technology/gate_libraries.rst
  docs/technology/simulation.rst
  experiments/physical_design_with_on_the_fly_gate_design/physical_design_with_on_the_fly_gate_design.cpp
  experiments/skeleton_bestagons_with_tags/skeleton_hex_inputsdbp_1i1o_diagonal.sqd
  experiments/skeleton_bestagons_with_tags/skeleton_hex_inputsdbp_1i1o_straight.sqd
  experiments/skeleton_bestagons_with_tags/skeleton_hex_inputsdbp_1i2o.sqd
  experiments/skeleton_bestagons_with_tags/skeleton_hex_inputsdbp_2i1o.sqd
  experiments/skeleton_bestagons_with_tags/skeleton_hex_inputsdbp_2i2o.sqd
  include/fiction/algorithms/network_transformation/technology_mapping.hpp
  include/fiction/algorithms/physical_design/apply_gate_library.hpp
  include/fiction/algorithms/physical_design/design_sidb_gates.hpp
  include/fiction/algorithms/physical_design/exact.hpp
  include/fiction/algorithms/physical_design/on_the_fly_circuit_design_on_defective_surface.hpp
  include/fiction/algorithms/properties/count_gate_types.hpp
  include/fiction/algorithms/simulation/sidb/quickexact.hpp
  include/fiction/algorithms/simulation/sidb/random_sidb_layout_generator.hpp
  include/fiction/io/dot_drawers.hpp
  include/fiction/io/print_layout.hpp
  include/fiction/io/read_sidb_surface_defects.hpp
  include/fiction/layouts/bounding_box.hpp
  include/fiction/layouts/coordinates.hpp
  include/fiction/layouts/gate_level_layout.hpp
  include/fiction/networks/technology_network.hpp
  include/fiction/technology/inml_topolinano_library.hpp
  include/fiction/technology/is_sidb_gate_design_impossible.hpp
  include/fiction/technology/qca_one_library.hpp
  include/fiction/technology/sidb_bestagon_library.hpp
  include/fiction/technology/sidb_defect_surface.hpp
  include/fiction/technology/sidb_defects.hpp
  include/fiction/technology/sidb_on_the_fly_gate_library.hpp
  include/fiction/technology/sidb_skeleton_bestagon_library.hpp
  include/fiction/technology/sidb_surface_analysis.hpp
  include/fiction/technology/technology_mapping_library.hpp
  include/fiction/traits.hpp
  include/fiction/utils/layout_utils.hpp
  test/algorithms/network_transformation/technology_mapping.cpp
  test/algorithms/physical_design/design_sidb_gates.cpp
  test/algorithms/simulation/sidb/quickexact.cpp
  test/io/print_layout.cpp
  test/layouts/bounding_box.cpp
  test/layouts/coordinates.cpp
  test/networks/technology_network.cpp
  test/technology/is_sidb_gate_design_impossible.cpp
  test/technology/sidb_bestagon_gate_library.cpp
  test/technology/sidb_defect_surface.cpp
  test/technology/sidb_defects.cpp
  test/technology/sidb_on_the_fly_gate_library.cpp
  test/technology/sidb_skeleton_bestagon_library.cpp
Labels: enhancement

#500 ✨ Extended Time-to-Solution Function
  bindings/pyfiction/include/pyfiction/algorithms/simulation/sidb/sidb_simulation_engine.hpp
  bindings/pyfiction/include/pyfiction/algorithms/simulation/sidb/time_to_solution.hpp
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/pyfiction/include/pyfiction/technology/charge_distribution_surface.hpp
  bindings/pyfiction/test/algorithms/simulation/sidb/test_time_to_solution.py
  docs/algorithms/sidb_simulation.rst
  docs/technology/simulation.rst
  include/fiction/algorithms/simulation/sidb/is_ground_state.hpp
  include/fiction/algorithms/simulation/sidb/quickexact.hpp
  include/fiction/algorithms/simulation/sidb/sidb_simulation_engine.hpp
  include/fiction/algorithms/simulation/sidb/sidb_simulation_result.hpp
  include/fiction/algorithms/simulation/sidb/time_to_solution.hpp
  include/fiction/technology/charge_distribution_surface.hpp
  test/algorithms/simulation/sidb/determine_the_groundstate_from_simulation_results.cpp
  test/algorithms/simulation/sidb/is_ground_state.cpp
  test/algorithms/simulation/sidb/is_groundstate.cpp
  test/algorithms/simulation/sidb/time_to_solution.cpp
  test/technology/charge_distribution_surface.cpp
Labels: enhancement

#506 :bug: Fixed a RST documentation bug that prevented `exact` and `exact_with_blacklist` to be rendered properly
  docs/algorithms/exact.rst
Labels: documentation, small fix

#504 :bookmark: Bump version to 0.6.3
  CMakeLists.txt
  docs/changelog.rst
  docs/conf.py
  pyproject.toml
Labels: versioning

#505 :bug: clang-tidy comments were not posted
  .github/workflows/clang-tidy-review.yml
Labels: bug, github_actions

#508 📝 Add `gold` to README and docs
  README.md
  docs/cli.rst
Labels: documentation

#507 🚨 clang-tidy warnings
  .github/workflows/clang-tidy-review.yml
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  include/fiction/algorithms/physical_design/graph_oriented_layout_design.hpp
  include/fiction/algorithms/physical_design/orthogonal.hpp
  test/algorithms/physical_design/graph_oriented_layout_design.cpp
Labels: small fix

#511 :pencil2: Fixed a typo in robustness domain analysis
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  docs/algorithms/sidb_simulation.rst
  include/fiction/algorithms/simulation/sidb/displacement_robustness_domain.hpp
  test/algorithms/simulation/sidb/displacement_robustness_domain.cpp
Labels: small fix

#512 :sparkles: Squared Euclidean and Chebyshev distance functions
  bindings/pyfiction/include/pyfiction/algorithms/path_finding/distance.hpp
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/pyfiction/test/algorithms/path_finding/test_distance.py
  docs/algorithms/path_finding.rst
  docs/changelog.rst
  include/fiction/algorithms/path_finding/distance.hpp
  test/algorithms/path_finding/distance.cpp
Labels: enhancement

#513 :memo: Fix a few oversights in the RTD documentation of SiDB simulation functionality
  docs/algorithms/sidb_simulation.rst
Labels: documentation, small fix

#514 ✨ Track number of crossings
  bindings/pyfiction/include/pyfiction/algorithms/network_transformation/technology_mapping.hpp
  bindings/pyfiction/include/pyfiction/algorithms/physical_design/exact.hpp
  bindings/pyfiction/include/pyfiction/algorithms/physical_design/graph_oriented_layout_design.hpp
  bindings/pyfiction/include/pyfiction/algorithms/physical_design/orthogonal.hpp
  bindings/pyfiction/include/pyfiction/algorithms/physical_design/post_layout_optimization.hpp
  bindings/pyfiction/include/pyfiction/algorithms/physical_design/wiring_reduction.hpp
  bindings/pyfiction/include/pyfiction/algorithms/simulation/sidb/critical_temperature.hpp
  bindings/pyfiction/include/pyfiction/algorithms/simulation/sidb/time_to_solution.hpp
  bindings/pyfiction/include/pyfiction/algorithms/verification/equivalence_checking.hpp
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  cli/cmd/physical_design/exact.hpp
  cli/cmd/physical_design/gold.hpp
  cli/cmd/physical_design/onepass.hpp
  cli/cmd/physical_design/ortho.hpp
  cli/stores.hpp
  include/fiction/algorithms/physical_design/exact.hpp
  include/fiction/algorithms/physical_design/graph_oriented_layout_design.hpp
  include/fiction/algorithms/physical_design/one_pass_synthesis.hpp
  include/fiction/algorithms/physical_design/orthogonal.hpp
  include/fiction/algorithms/physical_design/post_layout_optimization.hpp
  include/fiction/algorithms/simulation/sidb/time_to_solution.hpp
  include/fiction/layouts/gate_level_layout.hpp
  test/layouts/gate_level_layout.cpp
Labels: enhancement

#515 :bug: Fixed disappearing clocking schemes when applying a gate library
  bindings/pyfiction/include/pyfiction/inout/write_svg_layout.hpp
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  cli/cmd/physical_design/ortho.hpp
  include/fiction/algorithms/physical_design/apply_gate_library.hpp
  include/fiction/io/write_svg_layout.hpp
  include/fiction/layouts/clocked_layout.hpp
  include/fiction/layouts/clocking_scheme.hpp
Labels: bug

#516 :bookmark: Bump version to 0.6.4
  CMakeLists.txt
  docs/changelog.rst
  docs/conf.py
  pyproject.toml
  setup.py
Labels: versioning
