Repository cda-tum/fiction, pull requests merged in 2024-06, with the labels that each got.

#465 💚 Fix compilation of Python wheels for Windows
  .github/workflows/pyfiction-pypi-deployment.yml
  .github/workflows/python-bindings.yml
  bindings/pyfiction/test/algorithms/simulation/sidb/test_critical_temperature.py
  test/benchmark/simulation.cpp
Labels: github_actions

#452 ⚡ Cleanup dangling PIs
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  include/fiction/algorithms/network_transformation/network_conversion.hpp
  include/fiction/io/network_reader.hpp
Labels: performance

#453 ⚡ Enable relocation of all 2-input gates during `post_layout_optimization`
  include/fiction/algorithms/physical_design/post_layout_optimization.hpp
Labels: small fix

#461 ✨ Flag for optimizing POs only
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  include/fiction/algorithms/physical_design/post_layout_optimization.hpp
  test/algorithms/physical_design/post_layout_optimization.cpp
Labels: enhancement
