Repository cda-tum/fiction, pull requests merged in 2024-03, with the labels that each got.

#388 🐛 Fixed bug in three-state simulation and duplicate cds results for ``QuickExact``.
  docs/algorithms/sidb_simulation.rst
  docs/utils/utils.rst
  experiments/equivalence_checking_exact_simulation/equivalence_checking_exact_simulation.cpp
  include/fiction/algorithms/physical_design/design_sidb_gates.hpp
  include/fiction/algorithms/simulation/sidb/check_simulation_results_for_equivalence.hpp
  include/fiction/algorithms/simulation/sidb/quickexact.hpp
  include/fiction/technology/charge_distribution_surface.hpp
  include/fiction/utils/layout_utils.hpp
  include/fiction/utils/math_utils.hpp
  test/algorithms/simulation/sidb/check_simulation_results_for_equivalence.cpp
  test/algorithms/simulation/sidb/quickexact.cpp
  test/benchmark/simulation.cpp
Labels: bug

#396 :bug: Fixed an inconsistency in SiDB layout printing
  include/fiction/io/print_layout.hpp
  test/io/print_layout.cpp
Labels: bug, small fix

#395 :art: Usability improvement by return type adjustments
  cli/cmd/technology/area.hpp
  cli/stores.hpp
  docs/technology/properties.rst
  experiments/bestagon/bestagon.cpp
  experiments/defect_aware_physical_design/defect_aware_physical_design.cpp
  experiments/hexagonalization/hexagonalization.cpp
  experiments/post_layout_optimization/post_layout_optimization.cpp
  include/fiction/algorithms/physical_design/exact.hpp
  include/fiction/algorithms/properties/critical_path_length_and_throughput.hpp
  include/fiction/algorithms/verification/equivalence_checking.hpp
  include/fiction/technology/area.hpp
  test/algorithms/physical_design/exact.cpp
  test/algorithms/properties/critical_path_length_and_throughput.cpp
  test/algorithms/verification/equivalence_checking.cpp
  test/utils/equivalence_checking_utils.hpp
Labels: enhancement, small fix

#401 :memo: Update ``QuickExact`` reference.
  docs/publications.rst
  include/fiction/algorithms/simulation/sidb/quickexact.hpp
Labels: documentation
