Repository cda-tum/fiction, pull requests merged in 2024-01, with the labels that each got.

#363 🐛 Fix floating-point errors.
  include/fiction/algorithms/simulation/sidb/operational_domain.hpp
  test/algorithms/simulation/sidb/operational_domain.cpp
Labels: bug

#364 🐛 Fixed hop energy calculation from neutral to positive SiDB
  include/fiction/technology/charge_distribution_surface.hpp
  test/algorithms/simulation/sidb/quickexact.cpp
Labels: bug

#370 :zap: Increased parallelism for building and testing in the Ubuntu and Windows workflows
  .github/workflows/codeql-analysis.yml
  .github/workflows/coverage.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
Labels: github_actions, performance

#372 :memo: Added latest paper references to the documentation
  docs/algorithms/post_layout_optimization.rst
  docs/algorithms/sidb_simulation.rst
  docs/publications.rst
  include/fiction/algorithms/physical_design/post_layout_optimization.hpp
  include/fiction/algorithms/simulation/sidb/operational_domain.hpp
  include/fiction/algorithms/simulation/sidb/quickexact.hpp
Labels: documentation

#375 🐛 Add round-function to mitigate floating precision issues
  include/fiction/algorithms/simulation/sidb/operational_domain.hpp
Labels: bug
