Repository cda-tum/fiction, pull requests merged in 2024-11, with the labels that each got.

#555 📥 Added SiQAD SiDB gate library
  experiments/operational_domain/operational_domain_3d_bestagon.cpp
  experiments/operational_domain/operational_domain_3d_siqad.cpp
  experiments/operational_domain/operational_domain_bestagon.cpp
  experiments/operational_domain/operational_domain_siqad.cpp
  experiments/sidb_gate_libraries/bestagon_gates/and.sqd
  experiments/sidb_gate_libraries/bestagon_gates/cx.sqd
  experiments/sidb_gate_libraries/bestagon_gates/fo2.sqd
  experiments/sidb_gate_libraries/bestagon_gates/ha.sqd
  experiments/sidb_gate_libraries/bestagon_gates/hourglass.sqd
  experiments/sidb_gate_libraries/bestagon_gates/inv.sqd
  experiments/sidb_gate_libraries/bestagon_gates/inv_diag.sqd
  experiments/sidb_gate_libraries/bestagon_gates/nand.sqd
  experiments/sidb_gate_libraries/bestagon_gates/nor.sqd
  experiments/sidb_gate_libraries/bestagon_gates/or.sqd
  experiments/sidb_gate_libraries/bestagon_gates/wire.sqd
  experiments/sidb_gate_libraries/bestagon_gates/wire_diag.sqd
  experiments/sidb_gate_libraries/bestagon_gates/xnor.sqd
  experiments/sidb_gate_libraries/bestagon_gates/xor.sqd
  experiments/sidb_gate_libraries/siqad_gates/and.sqd
  experiments/sidb_gate_libraries/siqad_gates/nand.sqd
  experiments/sidb_gate_libraries/siqad_gates/or.sqd
  experiments/sidb_gate_libraries/siqad_gates/xnor.sqd
  experiments/sidb_gate_libraries/siqad_gates/xor.sqd
  experiments/sidb_simulation/electrostatic_ground_state/runtime_analysis_bestagon_gates.cpp
  experiments/sidb_simulation/temperature/critical_temperature_simulation_bestagon.cpp
  experiments/sidb_simulation/temperature/critical_temperature_simulation_siqad.cpp
Labels: enhancement

#559 :rotating_light: Fixed compiler and linter warnings
  bindings/pyfiction/include/pyfiction/algorithms/iter/bdl_input_iterator.hpp
  bindings/pyfiction/include/pyfiction/algorithms/simulation/logic_simulation.hpp
  bindings/pyfiction/include/pyfiction/layouts/coordinates.hpp
  bindings/pyfiction/include/pyfiction/layouts/gate_level_layout.hpp
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  include/fiction/algorithms/graph/graph_coloring.hpp
  include/fiction/algorithms/iter/bdl_input_iterator.hpp
  include/fiction/algorithms/physical_design/apply_gate_library.hpp
  include/fiction/algorithms/simulation/sidb/detect_bdl_wires.hpp
  include/fiction/algorithms/simulation/sidb/displacement_robustness_domain.hpp
  include/fiction/io/read_sidb_surface_defects.hpp
  include/fiction/layouts/clocking_scheme.hpp
  include/fiction/layouts/gate_level_layout.hpp
  include/fiction/technology/charge_distribution_surface.hpp
  include/fiction/technology/sidb_on_the_fly_gate_library.hpp
  include/fiction/utils/layout_utils.hpp
  test/algorithms/simulation/sidb/displacement_robustness_domain.cpp
  test/io/read_sqd_layout.cpp
Labels: small fix

#561 :green_heart: Added ``fiction`` namespace to function to fix the Windows CI
  include/fiction/algorithms/simulation/sidb/displacement_robustness_domain.hpp
Labels: compiler issue

#553 🐛 Fixed several bugs resulting from the new ``cell_type::LOGIC`` in the SiDB technology
  include/fiction/io/read_sqd_layout.hpp
  include/fiction/io/write_sqd_layout.hpp
  include/fiction/technology/sidb_on_the_fly_gate_library.hpp
  test/io/read_sqd_layout.cpp
  test/io/write_sqd_layout.cpp
Labels: bug

#558 :whale: Improved the Docker workflow
  .dockerignore
  .github/workflows/docker-image.yml
  Dockerfile
  README.md
Labels: github_actions, docker

#564 🐍 Use `pybind's` print function to output the DRV report
  bindings/pyfiction/include/pyfiction/algorithms/verification/design_rule_violations.hpp
Labels: python

#566 🐛 Adapted optimization algorithms to handle layouts with PIs not placed at borders
  docs/changelog.rst
  include/fiction/algorithms/physical_design/post_layout_optimization.hpp
  include/fiction/algorithms/physical_design/wiring_reduction.hpp
  test/algorithms/physical_design/post_layout_optimization.cpp
  test/algorithms/physical_design/wiring_reduction.cpp
  test/benchmark/post_layout_optimization.cpp
  test/utils/blueprints/layout_blueprints.hpp
Labels: bug

#571 📝 Added wiring reduction paper to publication list
  docs/changelog.rst
  docs/publications.rst
Labels: documentation

#570 :green_heart: Remove explicit XCode version setup for macOS 13
  .github/workflows/macos.yml
Labels: bug, github_actions

#572 :apple: Adjusted deployment target for macOS
  .github/workflows/pyfiction-pypi-deployment.yml
  pyproject.toml
Labels: github_actions

#575 :snake: Expose `layout.get_name`
  bindings/pyfiction/include/pyfiction/layouts/gate_level_layout.hpp
  bindings/pyfiction/test/layouts/test_gate_level_layout.py
Labels: python

#577 :construction_worker: Attest build provenance to our wheels and sdist
  .github/workflows/pyfiction-pypi-deployment.yml
Labels: github_actions, python

#582 :bug: Fix Microsoft logo in CI badge by replacing the logo slug with a base64 encoding of the SVG image
  README.md
Labels: documentation, small fix

#580 :whale: Unify Dockerfile labels to conform to the Open Container Initiative (OCI) standard
  Dockerfile
Labels: docker

#574 ✅ Update Unit Tests and Exclude Long-Running Tests in Debug Mode Using ``NDEBUG``
  test/algorithms/physical_design/design_sidb_gates.cpp
  test/algorithms/simulation/sidb/critical_temperature.cpp
  test/algorithms/simulation/sidb/is_operational.cpp
  test/algorithms/simulation/sidb/quickexact.cpp
Labels: enhancement

#565 ✨ Added function to print SiDB layout to svg
  bindings/pyfiction/include/pyfiction/inout/write_svg_layout.hpp
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/pyfiction/include/pyfiction/utils/version_info.hpp
  bindings/pyfiction/pyfiction.cpp
  bindings/pyfiction/test/inout/test_write_svg_layout.py
  cli/stores.hpp
  docs/io/visualization.rst
  include/fiction/io/write_svg_layout.hpp
  test/io/write_qca_layout.cpp
  test/io/write_svg_layout.cpp
Labels: enhancement

#581 :memo: Added Willem Lambooy as author to the framework
  docs/conf.py
  pyproject.toml
Labels: documentation

#573 :sparkles: Restructured Critical Temperature simulation with kink control option
  bindings/pyfiction/include/pyfiction/algorithms/simulation/sidb/calculate_energy_and_state_type.hpp
  bindings/pyfiction/include/pyfiction/algorithms/simulation/sidb/critical_temperature.hpp
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/pyfiction/test/algorithms/simulation/sidb/test_critical_temperature.py
  cli/cmd/simulation/temp.hpp
  docs/algorithms/sidb_simulation.rst
  experiments/sidb_simulation/temperature/critical_temperature_simulation_siqad.cpp
  include/fiction/algorithms/simulation/sidb/calculate_energy_and_state_type.hpp
  include/fiction/algorithms/simulation/sidb/critical_temperature.hpp
  include/fiction/algorithms/simulation/sidb/is_operational.hpp
  include/fiction/algorithms/simulation/sidb/verify_logic_match.hpp
  test/algorithms/simulation/sidb/can_positive_charges_occur.cpp
  test/algorithms/simulation/sidb/critical_temperature.cpp
  test/algorithms/simulation/sidb/is_operational.cpp
  test/algorithms/simulation/sidb/operational_domain.cpp
  test/algorithms/simulation/sidb/verify_logic_match.cpp
  test/utils/blueprints/layout_blueprints.hpp
Labels: enhancement

#585 :bug: Enforce runtime evaluation of dynamic formatting strings to fix `consteval` contexts
  include/fiction/io/print_layout.hpp
  include/fiction/io/write_svg_layout.hpp
  include/fiction/layouts/coordinates.hpp
  include/fiction/technology/cell_ports.hpp
Labels: small fix

#590 ✨ Add option to hide lattice points in the SiDB layout SVG writer
  bindings/pyfiction/include/pyfiction/inout/write_svg_layout.hpp
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  include/fiction/io/write_svg_layout.hpp
  test/io/write_svg_layout.cpp
Labels: enhancement

#591 :memo: Update the CHANGELOG
  docs/changelog.rst
Labels: documentation

#593 :memo: Added defect-aware physical design paper from DATE 2024.
  docs/publications.rst
Labels: documentation

#587 :sparkles: Add function to detect if non-operational status is due to wire kink
  bindings/pyfiction/include/pyfiction/algorithms/simulation/sidb/is_operational.hpp
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/pyfiction/test/algorithms/simulation/sidb/test_is_operational.py
  docs/algorithms/sidb_simulation.rst
  docs/changelog.rst
  include/fiction/algorithms/simulation/sidb/is_operational.hpp
  include/fiction/algorithms/simulation/sidb/operational_domain.hpp
  include/fiction/algorithms/simulation/sidb/verify_logic_match.hpp
  test/algorithms/simulation/sidb/is_operational.cpp
Labels: enhancement

#594 :bug: Fixed ``design_sidb_gates`` function for skeletons with east-facing I/O pins.
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  docs/changelog.rst
  include/fiction/algorithms/physical_design/design_sidb_gates.hpp
  include/fiction/algorithms/simulation/sidb/is_operational.hpp
  test/algorithms/physical_design/design_sidb_gates.cpp
  test/utils/blueprints/layout_blueprints.hpp
Labels: bug

#595 :alembic: Added pruning information to ``QuickCell`` experiment.
  docs/changelog.rst
  experiments/quickcell/quickcell_3_input.cpp
  experiments/quickcell/quickcell_vs_automatic_exhaustive_2_input.cpp
Labels: enhancement
