Repository cda-tum/fiction, pull requests merged in 2024-09, with the labels that each got.

#510 :memo: Added documentation on our latest papers from IEEE NANO
  README.md
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  docs/algorithms/determine_clocking.rst
  docs/publications.rst
  docs/technology/hsi_lattices.rst
  experiments/physical_design_with_on_the_fly_gate_design/physical_design_with_on_the_fly_gate_design.cpp
  include/fiction/algorithms/physical_design/determine_clocking.hpp
  include/fiction/algorithms/physical_design/graph_oriented_layout_design.hpp
  include/fiction/algorithms/physical_design/on_the_fly_circuit_design_on_defective_surface.hpp
  include/fiction/algorithms/physical_design/post_layout_optimization.hpp
Labels: documentation

#519 :rotating_light: Fixed clang-tidy warnings.
  include/fiction/algorithms/optimization/simulated_annealing.hpp
  include/fiction/algorithms/physical_design/design_sidb_gates.hpp
  include/fiction/algorithms/physical_design/on_the_fly_circuit_design_on_defective_surface.hpp
  include/fiction/algorithms/simulation/sidb/assess_physical_population_stability.hpp
  include/fiction/algorithms/simulation/sidb/critical_temperature.hpp
  include/fiction/algorithms/simulation/sidb/displacement_robustness_domain.hpp
  include/fiction/algorithms/simulation/sidb/maximum_defect_influence_position_and_distance.hpp
  include/fiction/algorithms/simulation/sidb/occupation_probability_of_excited_states.hpp
  include/fiction/algorithms/simulation/sidb/quickexact.hpp
  include/fiction/algorithms/simulation/sidb/random_sidb_layout_generator.hpp
  include/fiction/algorithms/simulation/sidb/sidb_simulation_engine.hpp
  include/fiction/algorithms/simulation/sidb/time_to_solution.hpp
  include/fiction/io/write_sqd_layout.hpp
  include/fiction/io/write_sqd_sim_result.hpp
  include/fiction/layouts/bounding_box.hpp
  include/fiction/technology/sidb_defects.hpp
Labels: small fix

#522 :wrench: Attempt to calm down `clang-tidy`
  .clang-tidy
  experiments/bestagon/bestagon.cpp
  experiments/defect_aware_physical_design/defect_aware_physical_design.cpp
  experiments/post_layout_optimization/post_layout_optimization.cpp
Labels: github_actions

#521 ✨ Extended BDL input iterator to support different SiDB input representations
  bindings/pyfiction/include/pyfiction/algorithms/iter/bdl_input_iterator.hpp
  bindings/pyfiction/include/pyfiction/algorithms/simulation/sidb/critical_temperature.hpp
  bindings/pyfiction/include/pyfiction/algorithms/simulation/sidb/is_operational.hpp
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/pyfiction/test/algorithms/simulation/sidb/test_displacement_robustness_domain.py
  cli/cmd/simulation/temp.hpp
  docs/algorithms/iterators.rst
  docs/changelog.rst
  docs/publications.rst
  experiments/sidb_simulation/electrostatic_ground_state/runtime_analysis.cpp
  experiments/sidb_simulation/temperature/critical_temperature_simulation_bestagon.cpp
  experiments/sidb_simulation/temperature/critical_temperature_simulation_siqad.cpp
  include/fiction/algorithms/iter/bdl_input_iterator.hpp
  include/fiction/algorithms/physical_design/design_sidb_gates.hpp
  include/fiction/algorithms/simulation/sidb/calculate_energy_and_state_type.hpp
  include/fiction/algorithms/simulation/sidb/critical_temperature.hpp
  include/fiction/algorithms/simulation/sidb/is_operational.hpp
  include/fiction/algorithms/simulation/sidb/random_sidb_layout_generator.hpp
  include/fiction/technology/is_sidb_gate_design_impossible.hpp
  include/fiction/utils/truth_table_utils.hpp
  test/algorithms/simulation/sidb/critical_temperature.cpp
  test/algorithms/simulation/sidb/displacement_robustness_domain.cpp
  test/algorithms/simulation/sidb/is_operational.cpp
  test/algorithms/simulation/sidb/quickexact.cpp
  test/utils/blueprints/layout_blueprints.hpp
Labels: enhancement

#525 ✨ `gold` with discretionary cost objectives
  bindings/pyfiction/include/pyfiction/algorithms/physical_design/graph_oriented_layout_design.hpp
  bindings/pyfiction/include/pyfiction/layouts/gate_level_layout.hpp
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/pyfiction/test/algorithms/physical_design/test_graph_oriented_layout_design.py
  cli/cmd/physical_design/gold.hpp
  experiments/graph_oriented_layout_design/gold_cost_objectives.cpp
  experiments/graph_oriented_layout_design/graph_oriented_layout_design.cpp
  include/fiction/algorithms/physical_design/graph_oriented_layout_design.hpp
  test/algorithms/physical_design/graph_oriented_layout_design.cpp
  test/benchmark/graph_oriented_layout_design.cpp
Labels: enhancement

#520 ⚗️ Added a runtime script for three state simulation and apply small changes.
  bindings/pyfiction/include/pyfiction/algorithms/physical_design/design_sidb_gates.hpp
  bindings/pyfiction/include/pyfiction/algorithms/simulation/sidb/random_sidb_layout_generator.hpp
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/pyfiction/test/algorithms/physical_design/test_design_sidb_gates.py
  bindings/pyfiction/test/algorithms/simulation/sidb/test_random_sidb_layout_generator.py
  docs/changelog.rst
  experiments/physical_design_with_on_the_fly_gate_design/physical_design_with_on_the_fly_gate_design.cpp
  experiments/random_sidb_layout_generation/random_sidb_layout_generation.cpp
  experiments/sidb_simulation/electrostatic_ground_state/runtime_analysis_bestagon_gates.cpp
  experiments/sidb_simulation/electrostatic_ground_state/runtime_analysis_layouts_with_possible_positive_sidbs.cpp
  experiments/sidb_simulation/temperature/critical_temperature_simulation_bestagon.cpp
  include/fiction/algorithms/physical_design/design_sidb_gates.hpp
  include/fiction/algorithms/simulation/sidb/critical_temperature.hpp
  include/fiction/algorithms/simulation/sidb/random_sidb_layout_generator.hpp
  include/fiction/technology/charge_distribution_surface.hpp
  include/fiction/technology/fcn_gate_library.hpp
  include/fiction/technology/sidb_on_the_fly_gate_library.hpp
  include/fiction/utils/layout_utils.hpp
  test/algorithms/physical_design/design_sidb_gates.cpp
  test/algorithms/simulation/sidb/random_sidb_layout_generator.cpp
  test/utils/layout_utils.cpp
Labels: enhancement

#518 ✨ Added support for optional input parameter points in flood fill
  bindings/pyfiction/include/pyfiction/algorithms/simulation/sidb/compute_operational_ratio.hpp
  bindings/pyfiction/include/pyfiction/algorithms/simulation/sidb/operational_domain.hpp
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/pyfiction/pyfiction.cpp
  bindings/pyfiction/test/algorithms/simulation/sidb/test_compute_operational_ratio.py
  bindings/pyfiction/test/algorithms/simulation/sidb/test_is_operational.py
  bindings/pyfiction/test/algorithms/simulation/sidb/test_operational_domain.py
  bindings/pyfiction/test/resources/21_hex_inputsdbp_and_v19.sqd
  bindings/pyfiction/test/resources/AND_mu_032_111_surface.sqd
  cli/cmd/simulation/opdom.hpp
  docs/algorithms/sidb_simulation.rst
  include/fiction/algorithms/simulation/sidb/compute_operational_ratio.hpp
  include/fiction/algorithms/simulation/sidb/operational_domain.hpp
  include/fiction/io/print_layout.hpp
  include/fiction/utils/layout_utils.hpp
  test/algorithms/simulation/sidb/compute_operational_ratio.cpp
  test/algorithms/simulation/sidb/operational_domain.cpp
  test/io/print_layout.cpp
  test/utils/blueprints/layout_blueprints.hpp
Labels: enhancement
