Repository cda-tum/fiction, pull requests merged in 2024-02, with the labels that each got.

#374 :white_check_mark: Add more tests for 3-state simulation.
  test/algorithms/simulation/sidb/exhaustive_ground_state_simulation.cpp
  test/algorithms/simulation/sidb/quickexact.cpp
Labels: enhancement

#376 :construction_worker: Update macOS CI to support Apple Silicon runners
  .github/workflows/macos.yml
Labels: github_actions

#381 :sparkles: SAT-based clock number assignment
  docs/algorithms/algorithms.rst
  docs/algorithms/apply_gate_library.rst
  docs/algorithms/color_routing.rst
  docs/algorithms/determine_clocking.rst
  docs/algorithms/exact.rst
  docs/algorithms/graph.rst
  docs/algorithms/one_pass_synthesis.rst
  docs/algorithms/orthogonal.rst
  docs/algorithms/verification.rst
  include/fiction/algorithms/physical_design/determine_clocking.hpp
  include/fiction/layouts/clocking_scheme.hpp
  include/fiction/layouts/gate_level_layout.hpp
  include/fiction/layouts/synchronization_element_layout.hpp
  test/algorithms/physical_design/determine_clocking.cpp
  test/benchmark/determine_clocking.cpp
  test/benchmark/distance_map.cpp
  test/layouts/gate_level_layout.cpp
  test/utils/blueprints/layout_blueprints.hpp
Labels: enhancement

#382 :memo: Added missing RST documentation
  docs/algorithms/sidb_simulation.rst
  include/fiction/algorithms/simulation/sidb/can_positive_charges_occur.hpp
Labels: documentation
