Repository cda-tum/fiction, pull requests merged in 2024-07, with the labels that each got.

#468 :green_heart: Update CodeQL workflow to avoid memory issue
  .github/workflows/codeql-analysis.yml
Labels: github_actions

#460 🐍 Update Post-Layout Optimization Bindings
  bindings/pyfiction/include/pyfiction/algorithms/physical_design/post_layout_optimization.hpp
  bindings/pyfiction/include/pyfiction/algorithms/physical_design/wiring_reduction.hpp
  bindings/pyfiction/test/algorithms/physical_design/test_post_layout_optimization.py
  bindings/pyfiction/test/algorithms/physical_design/test_wiring_reduction.py
Labels: python

#451 🐛 Multi-output nodes
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  include/fiction/algorithms/physical_design/orthogonal.hpp
  test/algorithms/physical_design/orthogonal.cpp
  test/utils/blueprints/network_blueprints.hpp
Labels: bug

#475 📝 Run python docstring generator on forks during PRs
  .github/workflows/pyfiction-docstring-generator.yml
Labels: github_actions

#472 🐛 Fixed multiple `post_layout_optimization` bugs
  include/fiction/algorithms/physical_design/post_layout_optimization.hpp
  include/fiction/algorithms/physical_design/wiring_reduction.hpp
Labels: bug

#477 📝 Update docstring generator to include target branch for push
  .github/workflows/pyfiction-docstring-generator.yml
Labels: bug

#480 🚨 Fixed compiler warnings
  include/fiction/algorithms/physical_design/post_layout_optimization.hpp
  include/fiction/algorithms/physical_design/wiring_reduction.hpp
Labels: small fix

#424 ✨ Algorithm for finding valid physical parameters for a given charge distribution.
  bindings/pyfiction/include/pyfiction/algorithms/simulation/sidb/assess_physical_population_stability.hpp
  bindings/pyfiction/include/pyfiction/algorithms/simulation/sidb/determine_physically_valid_parameters.hpp
  bindings/pyfiction/include/pyfiction/algorithms/simulation/sidb/operational_domain.hpp
  bindings/pyfiction/include/pyfiction/inout/write_operational_domain.hpp
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/pyfiction/pyfiction.cpp
  bindings/pyfiction/test/algorithms/simulation/sidb/test_assess_physical_population_stability.py
  bindings/pyfiction/test/algorithms/simulation/sidb/test_determine_physically_valid_parameters.py
  cli/cmd/simulation/opdom.hpp
  docs/algorithms/sidb_simulation.rst
  docs/io/physical_simulation.rst
  docs/utils/utils.rst
  experiments/operational_domain/operational_domain_siqad.cpp
  include/fiction/algorithms/simulation/sidb/assess_physical_population_stability.hpp
  include/fiction/algorithms/simulation/sidb/convert_potential_to_distance.hpp
  include/fiction/algorithms/simulation/sidb/determine_groundstate_from_simulation_results.hpp
  include/fiction/algorithms/simulation/sidb/determine_physically_valid_parameters.hpp
  include/fiction/algorithms/simulation/sidb/energy_distribution.hpp
  include/fiction/algorithms/simulation/sidb/operational_domain.hpp
  include/fiction/io/write_operational_domain.hpp
  include/fiction/technology/charge_distribution_surface.hpp
  include/fiction/utils/layout_utils.hpp
  test/algorithms/simulation/sidb/determine_physically_valid_parameters.cpp
  test/algorithms/simulation/sidb/operational_domain.cpp
  test/io/write_operational_domain.cpp
  test/utils/blueprints/layout_blueprints.hpp
Labels: enhancement

#482 :children_crossing: Add warning for leak sanitizer usage with AppleClang
  cmake/Sanitizers.cmake
Labels: compiler issue

#483 🎨 Utilizing tolerance to mitigate floating-point inaccuracies
  bindings/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/pyfiction/include/pyfiction/technology/charge_distribution_surface.hpp
  bindings/pyfiction/test/technology/test_charge_distribution_surface.py
  docs/technology/simulation.rst
  include/fiction/algorithms/simulation/sidb/energy_distribution.hpp
  include/fiction/algorithms/simulation/sidb/operational_domain.hpp
  include/fiction/technology/charge_distribution_surface.hpp
  include/fiction/utils/layout_utils.hpp
  test/algorithms/simulation/sidb/energy_distribution.cpp
  test/benchmark/simulation.cpp
  test/technology/charge_distribution_surface.cpp
Labels: bug

#486 👷 Disabled running computationally intensive unit tests via the CI in Debug build mode
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
  include/fiction/algorithms/simulation/sidb/operational_domain.hpp
  include/fiction/technology/charge_distribution_surface.hpp
  test/algorithms/physical_design/design_sidb_gates.cpp
  test/algorithms/simulation/sidb/assess_physical_population_stability.cpp
  test/algorithms/simulation/sidb/critical_temperature.cpp
  test/algorithms/simulation/sidb/determine_physically_valid_parameters.cpp
  test/algorithms/simulation/sidb/is_operational.cpp
  test/algorithms/simulation/sidb/maximum_defect_influence_position_and_distance.cpp
  test/algorithms/simulation/sidb/quickexact.cpp
Labels: github_actions, performance
