Repository cda-tum/fiction, pull requests merged in 2025-01, with the labels that each got.

#626 :wrench: Fix submodule management with Renovate
  .github/renovate.json5
Labels: bug, small fix, tooling

#605 :sparkles: ABC Callback
  README.md
  cli/CMakeLists.txt
  cli/cmd/io/read.hpp
  cli/cmd/logic/abc.hpp
  cli/cmd/physical_design/exact.hpp
  cli/commands.hpp
  docs/cli.rst
  docs/getting_started.rst
  libs/CMakeLists.txt
Labels: enhancement

#629 :snake: Drop Python 3.8 support due to its end-of-life status
  .readthedocs.yml
  docs/getting_started.rst
  noxfile.py
  pyproject.toml
Labels: python

#624 💚 Updated CI to support macOS 15
  .github/workflows/macos.yml
  .github/workflows/python-bindings.yml
Labels: github_actions

#602 :sparkles: Option for efficient determination of non-operational status
  bindings/mnt/pyfiction/include/pyfiction/algorithms/simulation/sidb/can_positive_charges_occur.hpp
  bindings/mnt/pyfiction/include/pyfiction/algorithms/simulation/sidb/is_operational.hpp
  bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/mnt/pyfiction/test/algorithms/simulation/sidb/test_is_operational.py
  docs/algorithms/sidb_simulation.rst
  docs/changelog.rst
  experiments/operational_domain/operational_domain_bestagon.cpp
  experiments/operational_domain/operational_domain_bestagon_exact_vs_sketch.cpp
  experiments/quickcell/quickcell_3_input.cpp
  experiments/quickcell/quickcell_rectangular_gate_library.cpp
  experiments/quickcell/quickcell_vs_automatic_exhaustive_2_input.cpp
  experiments/sidb_gate_libraries/bestagon_gates/cx.sqd
  experiments/sidb_gate_libraries/bestagon_gates/inv.sqd
  include/fiction/algorithms/iter/bdl_input_iterator.hpp
  include/fiction/algorithms/physical_design/design_sidb_gates.hpp
  include/fiction/algorithms/simulation/sidb/calculate_energy_and_state_type.hpp
  include/fiction/algorithms/simulation/sidb/critical_temperature.hpp
  include/fiction/algorithms/simulation/sidb/displacement_robustness_domain.hpp
  include/fiction/algorithms/simulation/sidb/is_operational.hpp
  include/fiction/algorithms/simulation/sidb/operational_domain.hpp
  include/fiction/algorithms/simulation/sidb/verify_logic_match.hpp
  include/fiction/layouts/cell_level_layout.hpp
  include/fiction/utils/truth_table_utils.hpp
  test/algorithms/iter/bdl_input_iterator.cpp
  test/algorithms/physical_design/design_sidb_gates.cpp
  test/algorithms/simulation/sidb/critical_temperature.cpp
  test/algorithms/simulation/sidb/is_operational.cpp
  test/algorithms/simulation/sidb/operational_domain.cpp
  test/algorithms/simulation/sidb/operational_domain_ratio.cpp
  test/algorithms/simulation/sidb/quickexact.cpp
  test/algorithms/simulation/sidb/random_sidb_layout_generator.cpp
  test/algorithms/simulation/sidb/verify_logic_match.cpp
  test/benchmark/simulation.cpp
  test/layouts/cell_level_layout.cpp
  test/utils/blueprints/layout_blueprints.hpp
Labels: enhancement

#633 :bookmark: Bump version to 0.6.7
  CITATION.cff
  CMakeLists.txt
  docs/changelog.rst
  docs/conf.py
  pyproject.toml
Labels: documentation

#635 :construction_worker: Added ARM64 CI runs on Linux
  .github/workflows/macos.yml
  .github/workflows/pyfiction-pypi-deployment.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
  include/fiction/io/dot_drawers.hpp
  include/fiction/technology/charge_distribution_surface.hpp
Labels: github_actions

#641 ✨ Added the SRS clocking scheme
  README.md
  bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  cli/cmd/physical_design/exact.hpp
  cli/cmd/physical_design/onepass.hpp
  docs/_static/srs.png
  docs/_static/srs.svg
  docs/changelog.rst
  docs/layouts/clocking_scheme.rst
  include/fiction/layouts/clocking_scheme.hpp
  test/algorithms/physical_design/exact.cpp
  test/layouts/clocking_scheme.cpp
Labels: enhancement

#643 ⚗️ Updated QuickCell experiment
  experiments/operational_domain/operational_domain_bestagon_exact_vs_sketch.cpp
  experiments/quicktrace/quicktrace_vs_grid_search_bestagon.cpp
Labels: bug

#644 🐍 Unique Wheel Names
  .github/workflows/pyfiction-pypi-deployment.yml
Labels: bug, github_actions, python

#645 :bookmark: Bump version to 0.6.8
  CITATION.cff
  CMakeLists.txt
  docs/changelog.rst
  docs/conf.py
  pyproject.toml
Labels: versioning

#653 :bug: Fixed layout resizing in `apply_gate_library`
  bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  include/fiction/algorithms/physical_design/apply_gate_library.hpp
Labels: bug
