Repository cda-tum/fiction, pull requests merged in 2025-03, with the labels that each got.

#680 ⚗️ Added total runtime to experiment script
  bindings/mnt/pyfiction/include/pyfiction/algorithms/simulation/sidb/sidb_simulation_result.hpp
  experiments/operational_domain/operational_domain_bestagon_grid_vs_sketch.cpp
Labels: documentation

#654 ✨ Added timeout for `QuickSim`
  bindings/mnt/pyfiction/include/pyfiction/algorithms/simulation/sidb/quicksim.hpp
  bindings/mnt/pyfiction/include/pyfiction/algorithms/simulation/sidb/sidb_simulation_result.hpp
  bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/mnt/pyfiction/include/pyfiction/technology/charge_distribution_surface.hpp
  bindings/mnt/pyfiction/test/algorithms/simulation/sidb/test_quicksim.py
  bindings/mnt/pyfiction/test/algorithms/simulation/sidb/test_sidb_simulation_result.py
  bindings/mnt/pyfiction/test/technology/test_charge_distribution_surface.py
  cli/cmd/simulation/quicksim.hpp
  include/fiction/algorithms/simulation/sidb/critical_temperature.hpp
  include/fiction/algorithms/simulation/sidb/is_operational.hpp
  include/fiction/algorithms/simulation/sidb/operational_domain.hpp
  include/fiction/algorithms/simulation/sidb/quicksim.hpp
  include/fiction/algorithms/simulation/sidb/sidb_simulation_result.hpp
  include/fiction/algorithms/simulation/sidb/time_to_solution.hpp
  include/fiction/technology/charge_distribution_surface.hpp
  test/algorithms/simulation/sidb/is_ground_state.cpp
  test/algorithms/simulation/sidb/quicksim.cpp
  test/algorithms/simulation/sidb/time_to_solution.cpp
Labels: enhancement

#686 🐛 Number of crossings calculation
  include/fiction/layouts/gate_level_layout.hpp
  test/layouts/gate_level_layout.cpp
Labels: bug

#689 :bug: Fixed LT, LE, GT, and LE gate handling in `gate_level_layout` and `write_`/`read_fgl_layout`
  bindings/mnt/pyfiction/include/pyfiction/layouts/gate_level_layout.hpp
  bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  include/fiction/io/read_fgl_layout.hpp
  include/fiction/io/write_fgl_layout.hpp
  include/fiction/layouts/gate_level_layout.hpp
  test/algorithms/verification/design_rule_violations.cpp
  test/io/read_fgl_layout.cpp
  test/layouts/gate_level_layout.cpp
  test/utils/blueprints/layout_blueprints.hpp
Labels: bug

#691 :memo: Documenation fix related to `bdl_input_iterator`
  bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  docs/algorithms/iterators.rst
  include/fiction/algorithms/iter/bdl_input_iterator.hpp
Labels: bug, documentation

#685 :bug: Increased tolerance to avoid undetected degeneracy and added forbidden BDL types in wire detection
  bindings/mnt/pyfiction/__init__.py
  bindings/mnt/pyfiction/include/pyfiction/algorithms/simulation/sidb/groundstate_from_simulation_result.hpp
  bindings/mnt/pyfiction/include/pyfiction/algorithms/simulation/sidb/sidb_simulation_result.hpp
  bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/mnt/pyfiction/pyfiction.cpp
  bindings/mnt/pyfiction/test/algorithms/simulation/sidb/test_clustercomplete.py
  bindings/mnt/pyfiction/test/algorithms/simulation/sidb/test_exhaustive_ground_state_simulation.py
  bindings/mnt/pyfiction/test/algorithms/simulation/sidb/test_groundstate_from_simulation_results.py
  bindings/mnt/pyfiction/test/algorithms/simulation/sidb/test_operational_domain.py
  bindings/mnt/pyfiction/test/algorithms/simulation/sidb/test_quickexact.py
  bindings/mnt/pyfiction/test/algorithms/simulation/sidb/test_quicksim.py
  bindings/mnt/pyfiction/test/algorithms/simulation/sidb/test_sidb_simulation_result.py
  docs/algorithms/sidb_simulation.rst
  experiments/sidb_simulation/electrostatic_ground_state/runtime_analysis_layouts_with_possible_positive_sidbs.cpp
  include/fiction/algorithms/simulation/sidb/defect_influence.hpp
  include/fiction/algorithms/simulation/sidb/detect_bdl_wires.hpp
  include/fiction/algorithms/simulation/sidb/groundstate_from_simulation_result.hpp
  include/fiction/algorithms/simulation/sidb/is_ground_state.hpp
  include/fiction/algorithms/simulation/sidb/is_operational.hpp
  include/fiction/algorithms/simulation/sidb/sidb_simulation_result.hpp
  test/algorithms/simulation/sidb/clustercomplete.cpp
  test/algorithms/simulation/sidb/exhaustive_ground_state_simulation.cpp
  test/algorithms/simulation/sidb/operational_domain.cpp
  test/algorithms/simulation/sidb/quickexact.cpp
  test/algorithms/simulation/sidb/quicksim.cpp
  test/algorithms/simulation/sidb/sidb_simulation_result.cpp
  test/algorithms/simulation/sidb/verify_logic_match.cpp
Labels: bug

#684 ⚗️ Added experiment for a comprehensive analysis of the critical temperature domain
  bindings/mnt/pyfiction/include/pyfiction/algorithms/simulation/sidb/operational_domain.hpp
  bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/mnt/pyfiction/test/algorithms/simulation/sidb/test_operational_domain.py
  experiments/operational_domain/critical_temperature_domain_bestagon.cpp
  include/fiction/algorithms/simulation/sidb/operational_domain.hpp
  test/algorithms/simulation/sidb/operational_domain.cpp
Labels: experiment

#700 🐛 Exclude ClusterComplete from simulation engine selection when ALGLIB is disabled
  bindings/mnt/pyfiction/include/pyfiction/algorithms/simulation/sidb/sidb_simulation_engine.hpp
  bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  include/fiction/algorithms/simulation/sidb/critical_temperature.hpp
  include/fiction/algorithms/simulation/sidb/is_operational.hpp
  include/fiction/algorithms/simulation/sidb/sidb_simulation_engine.hpp
  include/fiction/algorithms/simulation/sidb/time_to_solution.hpp
Labels: bug
