Repository cda-tum/fiction, pull requests merged in 2025-02, with the labels that each got.

#652 🩹 Non-critical fixes w.r.t. the `ClusterComplete` merge (#390)
  cli/cmd/simulation/clustercomplete.hpp
  experiments/equivalence_checking_exact_simulation/equivalence_checking_exact_simulation.cpp
Labels: small fix

#657 :bug: Prevented jemalloc from rebuilding in incremental builds
  cmake/FetchJemalloc.cmake
  cmake/Findjemalloc.cmake
  libs/CMakeLists.txt
Labels: bug

#666 🔖 Bump version to 0.6.9
  CITATION.cff
  CMakeLists.txt
  docs/changelog.rst
  docs/conf.py
  pyproject.toml
  uv.lock
Labels: documentation, versioning

#673 :snake: Fixed python bindings for critical temperature domain
  bindings/mnt/pyfiction/include/pyfiction/algorithms/simulation/sidb/operational_domain.hpp
  bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/mnt/pyfiction/test/algorithms/simulation/sidb/test_operational_domain.py
  include/fiction/algorithms/simulation/sidb/operational_domain.hpp
Labels: bug

#679 :art: Refactored ``QuickSim`` to remove magic number for upper limit calculation
  bindings/mnt/pyfiction/include/pyfiction/technology/charge_distribution_surface.hpp
  experiments/sidb_simulation/electrostatic_ground_state/runtime_analysis_bestagon_gates.cpp
  include/fiction/algorithms/simulation/sidb/clustercomplete.hpp
  include/fiction/algorithms/simulation/sidb/quickexact.hpp
  include/fiction/algorithms/simulation/sidb/quicksim.hpp
  include/fiction/technology/charge_distribution_surface.hpp
  test/algorithms/simulation/sidb/quicksim.cpp
  test/benchmark/simulation.cpp
  test/technology/charge_distribution_surface.cpp
Labels: enhancement

#678 :art: Refactored random layout design functions
  bindings/mnt/pyfiction/include/pyfiction/algorithms/simulation/sidb/random_sidb_layout_generator.hpp
  bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/mnt/pyfiction/include/pyfiction/technology/charge_distribution_surface.hpp
  bindings/mnt/pyfiction/test/algorithms/simulation/sidb/test_random_sidb_layout_generator.py
  experiments/random_sidb_layout_generation/random_sidb_layout_generation.cpp
  experiments/sidb_simulation/electrostatic_ground_state/runtime_analysis_layouts_with_possible_positive_sidbs.cpp
  include/fiction/algorithms/physical_design/design_sidb_gates.hpp
  include/fiction/algorithms/simulation/sidb/random_sidb_layout_generator.hpp
  test/algorithms/simulation/sidb/random_sidb_layout_generator.cpp
Labels: enhancement
