Repository cda-tum/fiction, pull requests merged in 2025-09, with the labels that each got.

#796 :bug: Fixed PO location in `post_layout_optimization`
  bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  experiments/wiring_reduction/wiring_reduction.cpp
  include/fiction/algorithms/physical_design/post_layout_optimization.hpp
  include/fiction/algorithms/physical_design/wiring_reduction.hpp
  test/algorithms/physical_design/post_layout_optimization.cpp
  test/algorithms/physical_design/wiring_reduction.cpp
  test/benchmark/post_layout_optimization.cpp
  test/utils/blueprints/layout_blueprints.hpp
Labels: bug

#819 :bug: Fixed PO extension in `hexagonalization`
  docs/changelog.rst
  include/fiction/algorithms/physical_design/hexagonalization.hpp
  test/algorithms/physical_design/hexagonalization.cpp
  test/utils/blueprints/layout_blueprints.hpp
Labels: bug

#828 :sparkles: Extended the `area` command to also report layout width and height in nanometers
  bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/mnt/pyfiction/include/pyfiction/technology/area.hpp
  cli/cmd/technology/area.hpp
  docs/changelog.rst
  docs/technology/properties.rst
  include/fiction/technology/area.hpp
  test/technology/area.cpp
Labels: enhancement

#839 📝 Update TCAD journal paper
  bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  docs/publications.rst
  include/fiction/algorithms/physical_design/wiring_reduction.hpp
Labels: documentation
