Repository cda-tum/fiction, pull requests merged in 2025-04, with the labels that each got.

#693 🐛 Fixed inconsistencies and various bugs in SiDB simulation/analysis
  bindings/mnt/pyfiction/__init__.py
  bindings/mnt/pyfiction/include/pyfiction/algorithms/simulation/sidb/energy_distribution.hpp
  bindings/mnt/pyfiction/include/pyfiction/algorithms/simulation/sidb/minimum_energy.hpp
  bindings/mnt/pyfiction/include/pyfiction/algorithms/simulation/sidb/occupation_probability_of_excited_states.hpp
  bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/mnt/pyfiction/include/pyfiction/technology/charge_distribution_surface.hpp
  bindings/mnt/pyfiction/test/algorithms/simulation/sidb/test_calculate_energy_and_state_type.py
  bindings/mnt/pyfiction/test/algorithms/simulation/sidb/test_critical_temperature.py
  bindings/mnt/pyfiction/test/algorithms/simulation/sidb/test_energy_distribution.py
  bindings/mnt/pyfiction/test/technology/test_charge_distribution_surface.py
  cli/cmd/simulation/clustercomplete.hpp
  cli/cmd/simulation/quickexact.hpp
  cli/cmd/simulation/quicksim.hpp
  docs/algorithms/sidb_simulation.rst
  docs/technology/simulation.rst
  docs/utils/utils.rst
  include/fiction/algorithms/simulation/sidb/calculate_energy_and_state_type.hpp
  include/fiction/algorithms/simulation/sidb/critical_temperature.hpp
  include/fiction/algorithms/simulation/sidb/energy_distribution.hpp
  include/fiction/algorithms/simulation/sidb/equivalence_check_for_simulation_results.hpp
  include/fiction/algorithms/simulation/sidb/is_operational.hpp
  include/fiction/algorithms/simulation/sidb/minimum_energy.hpp
  include/fiction/algorithms/simulation/sidb/occupation_probability_of_excited_states.hpp
  include/fiction/algorithms/simulation/sidb/operational_domain.hpp
  include/fiction/algorithms/simulation/sidb/physical_population_stability.hpp
  include/fiction/algorithms/simulation/sidb/sidb_simulation_result.hpp
  include/fiction/io/write_location_and_ground_state.hpp
  include/fiction/io/write_sqd_sim_result.hpp
  include/fiction/technology/charge_distribution_surface.hpp
  include/fiction/technology/constants.hpp
  test/algorithms/simulation/sidb/calculate_energy_and_state_type.cpp
  test/algorithms/simulation/sidb/clustercomplete.cpp
  test/algorithms/simulation/sidb/critical_temperature.cpp
  test/algorithms/simulation/sidb/energy_distribution.cpp
  test/algorithms/simulation/sidb/exhaustive_ground_state_simulation.cpp
  test/algorithms/simulation/sidb/is_operational.cpp
  test/algorithms/simulation/sidb/occupation_probability_of_excited_states.cpp
  test/algorithms/simulation/sidb/operational_domain.cpp
  test/algorithms/simulation/sidb/quickexact.cpp
  test/algorithms/simulation/sidb/quicksim.cpp
  test/algorithms/simulation/sidb/sidb_simulation_result.cpp
  test/technology/charge_distribution_surface.cpp
Labels: bug

#668 :white_check_mark: Added test for issue #667
  bindings/mnt/pyfiction/test/algorithms/simulation/sidb/test_quickexact.py
  bindings/mnt/pyfiction/test/resources/Bestagon_AND_mu_025_v0.sqd
Labels: test

#692 ✨ Parameter to move inputs/outputs to top/bottom border after `hexagonalization`
  bindings/mnt/pyfiction/__init__.py
  bindings/mnt/pyfiction/include/pyfiction/algorithms/physical_design/hexagonalization.hpp
  bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/mnt/pyfiction/test/algorithms/physical_design/test_hexagonalization.py
  cli/cmd/physical_design/hex.hpp
  docs/algorithms/hexagonalization.rst
  docs/changelog.rst
  docs/cli.rst
  experiments/hexagonalization/hexagonalization.cpp
  include/fiction/algorithms/path_finding/a_star.hpp
  include/fiction/algorithms/physical_design/hexagonalization.hpp
  include/fiction/algorithms/physical_design/wiring_reduction.hpp
  include/fiction/utils/placement_utils.hpp
  test/algorithms/physical_design/hexagonalization.cpp
  test/utils/blueprints/layout_blueprints.hpp
Labels: enhancement

#721 :bug: Use correct function for charge index calculation and fix base for TTS calculation
  include/fiction/algorithms/simulation/sidb/sidb_simulation_result.hpp
  include/fiction/algorithms/simulation/sidb/time_to_solution.hpp
  test/algorithms/simulation/sidb/time_to_solution.cpp
Labels: bug

#664 :art: Slightly faster ClusterComplete
  bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  include/fiction/algorithms/simulation/sidb/clustercomplete.hpp
  include/fiction/technology/sidb_cluster_hierarchy.hpp
  test/algorithms/simulation/sidb/clustercomplete.cpp
  test/benchmark/simulation.cpp
Labels: enhancement

#719 :memo: Fixed warnings in documentation
  bindings/mnt/pyfiction/__init__.py
  bindings/mnt/pyfiction/include/pyfiction/algorithms/simulation/sidb/time_to_solution.hpp
  bindings/mnt/pyfiction/include/pyfiction/networks/logic_networks.hpp
  docs/algorithms/network_transformation.rst
  docs/algorithms/sidb_simulation.rst
  docs/algorithms/verification.rst
  docs/io/physical_simulation.rst
  docs/io/visualization.rst
  docs/networks/virtual_pi_network.rst
  docs/technology/simulation.rst
Labels: bug, documentation

#731 :construction_worker: Set up documentation builds with `uv`
  .github/renovate.json5
  .readthedocs.yml
  docs/requirements.txt
  pyproject.toml
  uv.lock
Labels: dependencies, documentation, performance
