Repository cda-tum/fiction, pull requests merged in 2025-06, with the labels that each got.

#747 :bug: Fixed I/O cell handling in ``assign_cell_type``
  bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  include/fiction/algorithms/physical_design/design_sidb_gates.hpp
  include/fiction/layouts/cell_level_layout.hpp
  include/fiction/technology/is_sidb_gate_design_impossible.hpp
  test/algorithms/physical_design/design_sidb_gates.cpp
  test/layouts/cell_level_layout.cpp
Labels: bug

#760 🎨 Small changes in ``is_operational`` and added ``PRUNING_BASED`` option to gate design
  bindings/mnt/pyfiction/include/pyfiction/algorithms/physical_design/design_sidb_gates.hpp
  bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/mnt/pyfiction/test/algorithms/physical_design/test_design_sidb_gates.py
  include/fiction/algorithms/physical_design/design_sidb_gates.hpp
  include/fiction/algorithms/simulation/sidb/is_operational.hpp
  test/algorithms/physical_design/design_sidb_gates.cpp
  test/algorithms/simulation/sidb/is_operational.cpp
Labels: enhancement

#764 :white_check_mark: Added test for operational domain of SiQAD OR gate.
  bindings/mnt/pyfiction/test/algorithms/simulation/sidb/test_operational_domain.py
  bindings/mnt/pyfiction/test/resources/siqad_or_gate.sqd
  test/algorithms/simulation/sidb/operational_domain.cpp
Labels: test

#743 ✨ Maximum-effort mode for `gold`
  bindings/mnt/pyfiction/include/pyfiction/algorithms/network_transformation/fanout_substitution.hpp
  bindings/mnt/pyfiction/include/pyfiction/algorithms/physical_design/graph_oriented_layout_design.hpp
  bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  bindings/mnt/pyfiction/test/algorithms/network_transformation/test_fanout_substitution.py
  bindings/mnt/pyfiction/test/algorithms/physical_design/test_graph_oriented_layout_design.py
  cli/cmd/logic/fanouts.hpp
  cli/cmd/physical_design/gold.hpp
  docs/changelog.rst
  docs/cli.rst
  include/fiction/algorithms/network_transformation/fanout_substitution.hpp
  include/fiction/algorithms/physical_design/graph_oriented_layout_design.hpp
  test/algorithms/network_transformation/fanout_substitution.cpp
  test/algorithms/physical_design/graph_oriented_layout_design.cpp
  test/benchmark/graph_oriented_layout_design.cpp
Labels: enhancement

#762 ⚗️ Added further experiments for ``QuickCell``
  experiments/gate_skeletons/skeleton_3_input/3_in_1_out_skeleton_one.sqd
  experiments/gate_skeletons/skeleton_3_input/3_in_1_out_skeleton_two.sqd
  experiments/gate_skeletons/skeleton_3_input/3_in_2_out_skeleton.sqd
  experiments/gate_skeletons/skeleton_3_input/3_in_3_out_skeleton.sqd
  experiments/standard_cell_design/pruning_vs_simulation_scalability.cpp
  experiments/standard_cell_design/quickcell_3_input.cpp
  include/fiction/utils/truth_table_utils.hpp
Labels: experiment
