Repository cda-tum/fiction, pull requests merged in 2025-05, with the labels that each got.

#730 :bug: Fixed not setting Z dimension while determining aspect ratio for cell-level layout
  include/fiction/algorithms/physical_design/apply_gate_library.hpp
  include/fiction/layouts/cartesian_layout.hpp
  test/algorithms/physical_design/apply_gate_library.cpp
Labels: bug

#741 :snake: Add Pythonic dictionary-like interfaces to `operational_domain` and `critical_temperature_domain`
  bindings/mnt/pyfiction/include/pyfiction/algorithms/simulation/sidb/operational_domain.hpp
  bindings/mnt/pyfiction/test/algorithms/simulation/sidb/test_operational_domain.py
  bindings/mnt/pyfiction/test/inout/test_write_operational_domain.py
  include/fiction/algorithms/simulation/sidb/operational_domain.hpp
  include/fiction/algorithms/simulation/sidb/sidb_simulation_domain.hpp
Labels: enhancement, python

#720 🔖 bump version to 0.6.11
  CITATION.cff
  CMakeLists.txt
  docs/changelog.rst
  docs/conf.py
  pyproject.toml
  uv.lock
Labels: versioning

#753 📝 Added DATE 2025 reference
  bindings/mnt/pyfiction/include/pyfiction/pybind11_mkdoc_docstrings.hpp
  docs/publications.rst
  experiments/standard_cell_design/quickcell_3_input.cpp
  experiments/standard_cell_design/quickcell_rectangular_gate_library.cpp
  experiments/standard_cell_design/quickcell_vs_automatic_exhaustive_2_input.cpp
  include/fiction/algorithms/physical_design/design_sidb_gates.hpp
Labels: documentation
